### ISSUE TITLE
Check for OCEAN in marketplace flow onboarding

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#100]
Motivation: to smooth onboarding.

In marketplace_flow.md:
```
4. Alice creates a pool for trading her new datatokens
First, first get Rinkeby OCEAN via this faucet. [Links to https://faucet.rinkeby.oceanprotocol.com/]

Then, in Python:

pool = ocean.pool.create(
   token_address,
   data_token_amount=100.0,
   OCEAN_amount=10.0,
   from_wallet=alice_wallet
)
```

The call to `ocean.pool.create()` needs OCEAN. If the wallet has no OCEAN there will be a somewhat cryptic error that the call failed. But it doesn't give much details why. We can improve that by first checking if the account has OCEAN and telling the user if there isn't any.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean_pool.py", line 98, in create
    raise AssertionError(f'pool.setup failed: txId={tx_id}, receipt={pool.get_tx_receipt(tx_id)}')
AssertionError: pool.setup failed: txId=0x2b4a2ca167199d97c48c3335567f51195dac6757247527b7283c85129a0a985f, receipt=AttributeDict({'blockHash': HexBytes('0x1ea677ddc8876c4602b8c98340890531c211cc8415e86b4f4ea369ec9c802c7c'), 'blockNumber': 7863706, 'contractAddress': None, 'cumulativeGasUsed': 385357, 'from': '0xb5958ac6d6b062c0c9ed579fb1b488caa4f4e5ee', 'gasUsed': 364357, 'logs': [], 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'status': 0, 'to': '0xb10d7d6ea28f890a88b390a326bd0e7c94be575e', 'transactionHash': HexBytes('0x2b4a2ca167199d97c48c3335567f51195dac6757247527b7283c85129a0a985f'), 'transactionIndex': 1})
```

**Comment by trentmc** [comment]
Done in https://github.com/oceanprotocol/ocean.py/pull/104
