### ISSUE TITLE
Error in publishing asset to market (Temporary fix available too)

### ISSUE THREAD

**Issue by surajsjain** [oceanprotocol/ocean.py#103]
I was trying the quickstart for the marketplace flow and in the step where I had to resolve the _did_ (`asset = market_ocean.assets.resolve(did)`), I got the following error:

```
Traceback (most recent call last):
  File "path_to_virtual_env/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "path_to_virtual_env/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "path_to_virtual_env/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path_to_virtual_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "path_to_virtual_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "path_to_virtual_env/lib/python3.8/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "path_to_virtual_env/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f21c384d880>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path_to_virtual_env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "path_to_virtual_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "path_to_virtual_env/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/v1/aquarius/assets/ddo/did:op:Af8FFd0B61aD911A9A15bb62AB18aEbD840FB716 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21c384d880>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path_to_virtual_env/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 303, in resolve
    return resolve_asset(did, metadata_store_url=self._config.aquarius_url)
  File "path_to_virtual_env/lib/python3.8/site-packages/ocean_lib/assets/asset_resolver.py", line 35, in resolve_asset
    ddo = AquariusProvider.get_aquarius(metadata_url).get_asset_ddo(did)
  File "path_to_virtual_env/lib/python3.8/site-packages/ocean_utils/aquarius/aquarius.py", line 90, in get_asset_ddo
    response = self.requests_session.get(f'{self.url}/{did}').content
  File "path_to_virtual_env/lib/python3.8/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "path_to_virtual_env/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "path_to_virtual_env/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "path_to_virtual_env/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/v1/aquarius/assets/ddo/did:op:Af8FFd0B61aD911A9A15bb62AB18aEbD840FB716 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21c384d880>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I found out that it was trying to connect to the locally hosted instance of Aquarius from the following line of the error:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/v1/aquarius/assets/ddo/did:op:Af8FFd0B61aD911A9A15bb62AB18aEbD840FB716 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21c384d880>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

So, I changed headed over to the `ocean_assets.py` file and I made a temporary adjustment to the `resolve` function by changing the `metadata_store_url` to the hosted Aquarius instance (https://aquarius.rinkeby.oceanprotocol.com/). And now, the function is like:
```
def resolve(self, did: str) -> Asset:
        """
        When you pass a did retrieve the ddo associated.

        :param did: DID, str
        :return: Asset instance
        """
        return resolve_asset(did, metadata_store_url='https://aquarius.rinkeby.oceanprotocol.com/')
```

After this, everything just worked fine. But I couldn't trace where `aquarius_url` which was in the place of `https://aquarius.rinkeby.oceanprotocol.com/` was coming from, so I couldn't solve it completely. Can somebody please solve this or point me to where `aquarius_url` is coming from?

**Comment by trentmc** [comment]
FYI I just did a push to improve marketplace quickstart flow. Likely doesn't fully help you, but it's an fyi.

**Comment by trentmc** [comment]
> Can somebody please solve this or point me to where aquarius_url is coming from?

It's in ocean_lib/config.py.

```
trentmc@trentmcLnv:~/code/ocean.py$ cat ./ocean_lib/config.py|grep aquar
NAME_AQUARIUS_URL = 'aquarius.url'
        aquarius.url = http://localhost:5000
    def aquarius_url(self):
        """URL of aquarius component. (e.g.): http://myaquarius:5000."""
```

I have to run now, will check in later.

**Comment by trentmc** [comment]
> I found out that it was trying to connect to the locally hosted instance of Aquarius from the following line ..

Could you re- run through the marketplace flow now and see if you hit the same issue please?

Be sure to check that you have set the AQUARIUS_URL envvar to the rinkeby url, as the README directs near the beginning.

Thank you!

**Comment by surajsjain** [comment]
It's working now. Thanks!
