### ISSUE TITLE
TypeError when instantiating Datatoken object from address

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1070]
I encountered this while calculating nmse for predict-eth contestants. I was updating my code for ocean.py v2 ([github issue](https://github.com/oceanprotocol/predict-eth-judge/issues/2)).

To reproduce:

1. Do "Setup:installation" step in [simple ocean.py README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/data-nfts-and-datatokens-flow.md).

2. Run the following, which instantiates a Datatoken object from a given address.

Start python console, and run:
```python
import os

import brownie
from brownie.network import accounts

from ocean_lib.example_config import ExampleConfig
from ocean_lib.models.datatoken import Datatoken
from ocean_lib.ocean.ocean import Ocean
from ocean_lib.web3_internal.utils import connect_to_network

# create Ocean instance
connect_to_network("polygon")
config = ExampleConfig.get_config("polygon")
ocean = Ocean(config)

# create alice_wallet
alice_private_key = os.getenv('REMOTE_TEST_PRIVATE_KEY1')
alice_wallet = accounts.add(alice_private_key)
bal = accounts.at(alice_wallet.address).balance()
print(f"alice_wallet.address={alice_wallet.address}. bal={bal/1e18} MATIC")
assert bal > 0, "Alice needs MATIC"

# create datatoken object
dt_addr = "0xdf2857f2f9f1f2a227ca0f00c20190ff7d7a05a0" #known DT on polygon
dt_addr = brownie.web3.toChecksumAddress(dt_addr)
dt = Datatoken(brownie.web3, dt_addr)
```

The last line will give the following traceback:
```text
(venv) trentmc@trentmc-xps:~/code/pej$ python mytest.py 
alice_wallet.address=0xA54ABd42b11B7C97538CAD7C6A2820419ddF703E. bal=10.0 MATIC
Traceback (most recent call last):
  File "/home/trentmc/code/pej/mytest.py", line 26, in <module>
    dt = Datatoken(brownie.web3, dt_addr)
  File "/home/trentmc/code/pej/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 28, in wrapper
    check_types(*args, **kwargs)
  File "/home/trentmc/code/pej/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 21, in check_types
    raise TypeError(
TypeError: Expected type '<class 'dict'>' for attribute 'config_dict' but received type '<class 'brownie.network.web3.Web3'>')
```

**Comment by calina-c** [comment]
should be `Datatoken(config, dt_addr)`

**Comment by trentmc** [comment]
> should be `Datatoken(config, dt_addr)`

I see my mistake. Somehow I was looking at old code for ContractBase constructor, where it passes in web3 not config_dict. My bad. 

Therefore I'll change, and can likely close this issue.

**Comment by trentmc** [comment]
Wrong line:

```python
dt = Datatoken(brownie.web3, dt_addr)
```

Corrected line:
```python
dt = Datatoken(config, dt_addr)
```

Upon using the corrected line, it works. Closing.
