### ISSUE TITLE
Exception: Address not found for development. Please check your address file

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1174]
### Background

It seems that the recent changes broke the ability for ocean to connect to ganache. (Commit https://github.com/oceanprotocol/ocean.py/commit/236b88567304955a46dbd8d38010d9078958982e, from PR https://github.com/oceanprotocol/ocean.py/pull/1171, for issue https://github.com/oceanprotocol/ocean.py/issues/1164).

The error is easy to reproduce. Basically, try to do _anything_ with ocean. Here's one way..

- In [developers.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/developers.md), go through steps 1, 2, 3 on installation etc -- all good
- Then, in console: `cp network-config.sample ~/.brownie/network-config.yaml` (This needs to be in developers.md. But we're about to change that anyway, so let's not worry about it yet.)
- Did [simple-flow](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/data-nfts-and-datatokens-flow.md) step 1 "Setup in Python". This is connecting to network, setting wallets. All good.
- did simple-flow step 2 "Publish Data NFT & Datatoken". In Python console: `data_nft = ocean.create_data_nft('NFT1', 'NFT1', alice_wallet)`

This will fail, with: 
```text
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/contract_utils.py", line 60, in get_contracts_addresses
    raise Exception(
Exception: Address not found for development. Please check your address file
```

Full traceback below

### More digging

In python:
```python
from ocean_lib.web3_internal.contract_utils import \
    get_addresses_with_fallback, get_contracts_addresses
addresses = get_addresses_with_fallback(config)

addresses.keys()
```

Which returns: `dict_keys(['rinkeby', 'mumbai', 'ropsten', 'moonbase', 'polygon', 'bsc', 'energyweb', 'moonriver', 'mainnet', 'goerli', 'polygonedge', 'gaiaxtestnet'])`

Note that it does _not_ include a `development` key. 

Where does it get this dict from? Let's dig...

The first line of `get_addresses_with_fallback()` does the following. Let's do it too: 

```python
address_file = config.get("ADDRESS_FILE")
```

Then let's see the value:
```python
print(address_file)
```

Which returns: `PosixPath('/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/addresses/address.json')`

Good. That's what we expect. This is the address file from importing the ocean contracts addresses library.

But it doesn't have `development` entry in it. And, we shouldn't expect it to, that has to happen on-the-fly locally.

This points to possible fixes:
- _do_ add a `development` entry to that file. Con: it adds more coupling to contracts repo, on a value that could be arbitary
- have a special case for `development` in ` get_addresses_with_fallback()`. Yes, I like this one!

### Full traceback

(I removed the lines with typing)

```text
>>> data_nft = ocean.create_data_nft('NFT1', 'NFT1', alice_wallet)
Traceback (most recent call last):
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 141, in create_data_nft
    nft_factory = self.get_nft_factory()
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 186, in get_nft_factory
    nft_factory_address = get_address_of_type(
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/util.py", line 20, in get_address_of_type
    addresses = get_contracts_addresses(config_dict)
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/contract_utils.py", line 60, in get_contracts_addresses
    raise Exception(
Exception: Address not found for development. Please check your address file
```

**Comment by trentmc** [comment]
marked this as critical, because it's a showstopper to being able to test anything else locally
