### ISSUE TITLE
custom gas strategy fails with create_url_asset()

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1464]
**Describe the bug**

(In the `remove-brownie` branch. [PR](https://github.com/oceanprotocol/ocean.py/pull/1458/files#diff-12d79fcd362b1ba70b432897f1bae7a36a32012c9abb5ccd107ba7b8c8c1dc6f))

I went through the main-flow READMEs 1,2,3, both local & remote-testnet. Everything worked.

Then I tried READMEs/gas-strategy-remote.md. It fails at the following. (Appendix has full traceback.)
```text
>>> (data_nft, datatoken, ddo) = ocean.assets.create_url_asset(
...     name,
...     url,
...     tx_dict=tx_dict
... )

ValueError: {'message': 'Could not decode transaction: invalid RLP: remainder must be zero'
```

So I added a new test to test_ocean_assets.py to capture this. And tested it. It fails with the same error. (Appendix has full traceback.)
```
(venv) trentmc@trentmc-xps:~/code/ocean.py$ pytest ocean_lib/ocean/test/test_ocean_assets.py::test_create_url_asset_with_gas_strategy -s
...
 ValueError: {'message': 'Could not decode transaction: invalid RLP: remainder must be zero'
```

### Action done in branch

I pytest.mark.skip'd the new test and added it to the branch. [Here](https://github.com/oceanprotocol/ocean.py/pull/1458/commits/9170ad49d0b667ad16e7e0d226d53d68f1a8cf52). We can get to it once this big PR is merged.

### Potential related change in branch

There were changes in the branch related to gas. so it could be that this error is only in the branch. 

Here's the diff of the gas README:
 
https://github.com/oceanprotocol/ocean.py/pull/1458/files#diff-12d79fcd362b1ba70b432897f1bae7a36a32012c9abb5ccd107ba7b8c8c1dc6f

![diff](https://github.com/oceanprotocol/ocean.py/assets/5305452/a4d47c96-0ed8-42c9-9425-5352e087a447)

### Appendix: Traceback from README

```text
>>> #create data asset
>>> (data_nft, datatoken, ddo) = ocean.assets.create_url_asset(
...     name,
...     url,
...     tx_dict=tx_dict
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean_assets.py", line 241, in create_url_asset
    return self.create_bundled(files, tx_dict, asset_args)
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean_assets.py", line 330, in create_bundled
    data_nft, datatoken = self.data_nft_factory.create_with_erc20(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/models/data_nft_factory.py", line 141, in create_with_erc20
    receipt = self.createNftWithErc20(
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/contract_base.py", line 77, in wrap
    receipt = web3.eth.send_raw_transaction(signed_tx.rawTransaction)
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/web3/eth.py", line 831, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'message': 'Could not decode transaction: invalid RLP: remainder must be zero', 'stack': 'Error: Could not decode transaction: invalid RLP: remainder must be zero\n    at Function.fromString (/app/dist/node/1.js:2:244141)\n    at EthereumApi.eth_sendRawTransaction (/app/dist/node/1.js:2:91748)\n    at EthereumApi.n.value (/app/dist/node/1.js:2:247270)\n    at Object.execute (/app/dist/node/1.js:2:170833)\n    at RequestCoordinator.<anonymous> (/app/dist/node/1.js:2:170647)\n    at /app/dist/node/1.js:2:170913\n    at new Promise (<anonymous>)\n    at RequestCoordinator.queue (/app/dist/node/1.js:2:170755)\n    at Executor.execute (/app/dist/node/1.js:2:169320)\n    at EthereumProvider._requestRaw (/app/dist/node/1.js:2:135499)', 'code': -32700}
````

### Appendix: Traceback from unittest

```text
(venv) trentmc@trentmc-xps:~/code/ocean.py$ pytest ocean_lib/ocean/test/test_ocean_assets.py::test_create_url_asset_with_gas_strategy -s 
Test session starts (platform: linux, Python 3.10.12, pytest 6.2.5, pytest-sugar 0.9.7)
rootdir: /home/trentmc/code/ocean.py, configfile: pytest.ini
plugins: sugar-0.9.7, env-0.6.2, web3-5.31.3
collected 1 item                                                                                                                                                                                   


――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_create_url_asset_with_gas_strategy ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

config = {'ADDRESS_FILE': '/home/trentmc/.ocean/ocean-contracts/artifacts/address.json', 'CHAIN_ID': 8996, 'DOWNLOADS_PATH': 'consume-downloads', 'METADATA_CACHE_URI': 'http://172.15.0.5:5000', ...}
publisher_wallet = <eth_account.signers.local.LocalAccount object at 0x7ff6656325c0>, consumer_wallet = <eth_account.signers.local.LocalAccount object at 0x7ff6654afac0>
consumer_ocean = <ocean_lib.ocean.ocean.Ocean object at 0x7ff6654e94b0>, OCEAN = <ocean_lib.models.datatoken1.Datatoken1 object at 0x7ff6654ea620>

    @pytest.mark.integration
    def test_create_url_asset_with_gas_strategy(
        config, publisher_wallet, consumer_wallet, consumer_ocean, OCEAN
    ):
        """Directly models READMEs/gas-strategy-remote.md behavior"""
        data_provider = DataServiceProvider
        ocean_assets = OceanAssets(config, data_provider)
    
        priority_fee, max_fee = get_gas_fees()
    
        name = "Branin dataset"
        url = "https://raw.githubusercontent.com/trentmc/branin/main/branin.arff"
        tx_dict = {
            "from": publisher_wallet,
            "maxPriorityFeePerGas": priority_fee,
            "maxFeePerGas": max_fee,
        }
    
>       ddo = ocean_assets.create_url_asset(
            name,
            url,
            tx_dict,
            dt_template_index=1,
            wait_for_aqua=False,
            )

ocean_lib/ocean/test/test_ocean_assets.py:501: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.10/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
ocean_lib/ocean/ocean_assets.py:241: in create_url_asset
    return self.create_bundled(files, tx_dict, asset_args)
venv/lib/python3.10/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
ocean_lib/ocean/ocean_assets.py:330: in create_bundled
    data_nft, datatoken = self.data_nft_factory.create_with_erc20(
venv/lib/python3.10/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
ocean_lib/models/data_nft_factory.py:141: in create_with_erc20
    receipt = self.createNftWithErc20(
ocean_lib/web3_internal/contract_base.py:77: in wrap
    receipt = web3.eth.send_raw_transaction(signed_tx.rawTransaction)
venv/lib/python3.10/site-packages/web3/eth.py:831: in send_raw_transaction
    return self._send_raw_transaction(transaction)
venv/lib/python3.10/site-packages/web3/module.py:57: in caller
    result = w3.manager.request_blocking(method_str,
venv/lib/python3.10/site-packages/web3/manager.py:198: in request_blocking
    return self.formatted_response(response,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

response = {'error': {'code': -32700, 'message': 'Could not decode transaction: invalid RLP: remainder must be zero', 'stack': 'E.../node/1.js:2:169320)\n    at EthereumProvider._requestRaw (/app/dist/node/1.js:2:135499)'}, 'id': 20, 'jsonrpc': '2.0'}
params = ('0x02f9081582232423850c1c6436f085467060ebe88318528394ea9058b3a010879147886c6d6bc6a0b25b04d5f880b907a4f86b2bcf00000000...c160a4bcfa63153a4c7c3d6b554aca90017601d30be1a21e6ea07efa34563d0b1e206af08d84fc2b00395a4c4d25a78b96afa0fe44af36678c91',)
error_formatters = <cyfunction identity at 0x7ff66780f030>, null_result_formatters = <cyfunction identity at 0x7ff66780f030>

    @staticmethod
    def formatted_response(
        response: RPCResponse,
        params: Any,
        error_formatters: Optional[Callable[..., Any]] = None,
        null_result_formatters: Optional[Callable[..., Any]] = None,
    ) -> Any:
        if "error" in response:
            apply_error_formatters(error_formatters, response)
>           raise ValueError(response["error"])
E           ValueError: {'message': 'Could not decode transaction: invalid RLP: remainder must be zero', 'stack': 'Error: Could not decode transaction: invalid RLP: remainder must be zero\n    at Function.fromString (/app/dist/node/1.js:2:244141)\n    at EthereumApi.eth_sendRawTransaction (/app/dist/node/1.js:2:91748)\n    at EthereumApi.n.value (/app/dist/node/1.js:2:247270)\n    at Object.execute (/app/dist/node/1.js:2:170833)\n    at RequestCoordinator.<anonymous> (/app/dist/node/1.js:2:170647)\n    at /app/dist/node/1.js:2:170913\n    at new Promise (<anonymous>)\n    at RequestCoordinator.queue (/app/dist/node/1.js:2:170755)\n    at Executor.execute (/app/dist/node/1.js:2:169320)\n    at EthereumProvider._requestRaw (/app/dist/node/1.js:2:135499)', 'code': -32700}

venv/lib/python3.10/site-packages/web3/manager.py:171: ValueError

 ocean_lib/ocean/test/test_ocean_assets.py ⨯                                                                                                                                         100% ██████████
===================================================================================== short test summary info ======================================================================================
FAILED ocean_lib/ocean/test/test_ocean_assets.py::test_create_url_asset_with_gas_strategy - ValueError: {'message': 'Could not decode transaction: invalid RLP: remainder must be zero', 'stack':...

Results (0.99s):
       1 failed
         - ocean_lib/ocean/test/test_ocean_assets.py:483 test_create_url_asset_with_gas_strategy
```

**Comment by calina-c** [comment]
reinstated and ran with #1458.
