### ISSUE TITLE
marketplace quickstart: problems with running services

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#154]
**Is your feature request related to a problem? Please describe.**
A user was trying to go through marketplace quickstart. Here was his feedback:

```
here is the error I get when trying to perform step 5 and display the asset 'did' via the localhost:

Traceback (most recent call last):
File "publisher.py", line 14, in <module>
asset = market_ocean.assets.resolve(did)
File "/home/xyz/blockchain/ocean.py/oceanPy/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 303, in resolve
return resolve_asset(did, metadata_store_url=self._config.aquarius_url)
File "/home/xyz/blockchain/ocean.py/oceanPy/lib/python3.8/site-packages/ocean_lib/assets/asset_resolver.py", line 35, in resolve_asset
ddo = AquariusProvider.get_aquarius(metadata_url).get_asset_ddo(did)
File "/home/xyz/blockchain/ocean.py/oceanPy/lib/python3.8/site-packages/ocean_utils/aquarius/aquarius.py", line 98, in get_asset_ddo
raise ValueError(response.decode('UTF-8'))
ValueError: did:op:492a8484e073b3f832524e444D23a14A7dEF90de asset DID is not in OceanDB

this is the aqurius output too:
ERROR Dao.get -- asset with id did:op:492a8484e073b3f832524e444D23a14A7dEF90de was not found, original error was:NotFoundError(404, '{"_index":"oceandb","_type":"_doc","_id":"did:op:492a8484e073b3f832524e444D23a14A7dEF90de","found":false}')
2021-02-23 09:49:08,644 - aquarius - ERROR - get_ddo: NotFoundError(404, '{"_index":"oceandb","_type":"_doc","_id":"did:op:492a8484e073b3f832524e444D23a14A7dEF90de","found":false}')
2021-02-23 09:49:08 instance-2 werkzeug[87759] INFO 127.0.0.1 - - [23/Feb/2021 09:49:08] "GET /api/v1/aquarius/assets/ddo/did:op:492a8484e073b3f832524e444D23a14A7dEF90de HTTP/1.1" 404 -

Also in my humble opinion the marketplace_flow_md seems a little confused because it does not state as soon as it is necessary to launch the provider and the aquarius with their respective config."
```

**Describe the solution you'd like**
Ensure that the the quickstart works for users more reliably.

Note that just yesterday I tested quickstart end-to-end, it worked for me. --trentmc

The issue above was: the user was trying to run his own services. But the quickstart asks to use existing running services. In step 1 (setup) it asks the user to point to the urls with "export AQUARIUS_URL=https://aquarius.rinkeby.oceanprotocol.com..."

But if the user got tripped up, what will help is to clarify what services are to be used in the quickstart text. *That's* the goal of this issue.

**Comment by trentmc** [comment]
Fixed with https://github.com/oceanprotocol/ocean.py/commit/32ca223175aacd4c545de6fc37d80655175ef64a
