### ISSUE TITLE
create_data_token() fail when addresses not specified

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#185]
## Describe the bug

The following configuration fails:
- using barge
- import ocean.py (vs git clone)
- no config.ini file, just `NETWORK_URL=ganache`. Note that location of addresses artifacts is _not_ specified, with the expectation that there be good defaults.
- trying to do simple quickstart functionality 

This was first discovered during work on #113, in [this PR](https://github.com/oceanprotocol/ocean.py/pull/184). With the configuration above, it fails on the first real usage of ocean.py functionality: the call to `ocean.create_data_token()`.

There are two issues:
1. It logs a warning: `WARNING:root:No logs were found for tx 0xe62c7...`
2. `contract_handler.py::_load()` gives an error: `KeyError: ('DataTokenTemplate', '')`, which seems to be caused by the `address` value staying at `''`. 

Issue (1) is a sign that it can't see the smart contract addresses. Issue (2) is likely a result of (1).

Related: 
- #205 create_data_token() fail when using default CONFIG_FILE value.
- [multi-repo#83](https://github.com/oceanprotocol/multi-repo-issue/issues/83) ocean-contracts is hard to use in python, including in ocean.py

## To Reproduce

(This is like developers.md, but replacing `git clone` of ocean.py to `pip install` of it.)

**Run the services.** In a new console:
```console
#grab repo
git clone https://github.com/oceanprotocol/barge
cd barge

#clean up old containers (to be sure)
docker system prune -a --volumes

#run barge with provider on
./start_ocean.sh  --with-provider2
```

**Install the library; set envvars; go into py.** In a new console:
```console
#Initialize virtual environment and activate it.
python -m venv venv
source venv/bin/activate

#Install the ocean.py library
pip install ocean-lib

#set envvars
export TEST_PRIVATE_KEY1=0xc594c6e5def4bab63ac29eed19a134c130388f74f019bc74b8f4389df2837a58
export NETWORK_URL=ganache

#go into python
python
```

**Publish datatokens.** Within the py console:
```python
import os
from ocean_lib.ocean.ocean import Ocean
from ocean_lib.web3_internal.wallet import Wallet

private_key = os.getenv('TEST_PRIVATE_KEY1')
config = {'network': os.getenv('NETWORK_URL')}
ocean = Ocean(config)

print("create wallet: begin")
wallet = Wallet(ocean.web3, private_key=private_key)
print(f"create wallet: done. Its address is {wallet.address}")

print("create datatoken: begin.")
datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet) 
assert datatoken.address not in [None, '']
```

It fails on the last line. The second-last line gives a warning

## Expected behavior
It should create the datatokens successfully (no warnings or errors), while still using barge. 

**TODOs**

- [ ] Write a unit test to capture the KeyError issue in `contract_handler.py::_load()`; then update `_load()` to handle it better. 
- [ ] Get to the bottom of what's causing the warning; write a test; fix it
- [ ] Re-deploy

## Traceback-y stuff

Notes from initial commit:

First cut improving main README (reorg) and datatokens_flow.md. Just starting on marketplace_flow.md. However, errors occur in datatokens_flow.md, I think this has uncovered bugs, I need to resolve them before I go further here.

----
How I got the errors

* used the flow as described in the updated datatokens readme
* this used the most recent release of ocean-lib, which went into my local venv. 
* I debugged with pdb breakpoints in the venv. `~/code/play/venv/lib/python3.8/site-packages/ocean_lib/web3_internal/contract_handler.py`

Here's `contract_handler.py::_load` annotated to point out what I learned, and the main issues:
```python

    @staticmethod
    def _load(contract_name, address=None):
        """Retrieve the contract instance for `contract_name` that represent the smart
        contract in the ethereum network.

        :param contract_name: str name of the solidity smart contract.
        :param address: hex str -- address of smart contract
        :return: web3.eth.Contract instance
        """        
        assert (
            ContractHandler.artifacts_path is not None
        ), "artifacts_path should be already set."
        contract_definition = ContractHandler.read_abi_from_file(
            contract_name, ContractHandler.artifacts_path
        )

        #Debugging below is
        # from the modified datatokens readme,
        # final line, calling ocean.create_data_token
        # Before it gets here, I get a log message:
        # "WARNING:root:No logs were found for tx 0xe62c75b18ecdfd0f928eef3564f3573208c37c2e519cc1b456db6217a4d5b6bd."

        #Then I only got PDB to stop when
        # contract_name = 'DataTokenTemplate' (not 'DTFactory')
        # 

        # (Pdb) address
        # ''
        # (Pdb) "address" in contract_definition
        # False
                    
        if not address and "address" in contract_definition: #False, so skipped
            address = contract_definition.get("address")
            assert address, "Cannot find contract address in the abi file."
            address = Web3.toChecksumAddress(address)

        # (Pdb) address
        # ''
        
        abi = contract_definition["abi"]
        bytecode = contract_definition["bytecode"]
        contract = Web3Provider.get_web3().eth.contract(
            address=address, abi=abi, bytecode=bytecode
        )

        #(Pdb) ContractHandler._contracts[contract_name]
        #*** KeyError: 'DataTokenTemplate'

        ContractHandler._set(contract_name, contract)

        # (Pdb) ContractHandler._contracts[(contract_name, address)]
        # *** KeyError: ('DataTokenTemplate', '')
        # (Pdb) ContractHandler._contracts[contract_name]
        # (<class 'web3.utils.datatypes.Contract'>, <web3.contract.ConciseContract object at 0x7fbb3f777c70>)
        
        # Here's the bug!! The return value is always the ordinal-2 key,
        # but if address is still '' then it should use ordinal-1 key
        #
        # That will fix the error here. However the final line of quickstart:

        # >>> print(f"created datatoken: done. Its address is {datatoken.address}")
        # created datatoken: done. Its address is None

        # So maybe there are two bugs.
        # (1) Return value should handle when address=''.
        #     The fix for one is below (or assert != ''?)
        #     Either way, I should write a unit test. 
        # (2) Why is address='' in the first place, and warning "No logs where found for tx .." ?

        if address == '': #FIXED with if/else here
            return ContractHandler._contracts[contract_name]
        else:
            return ContractHandler._contracts[(contract_name, address)]
```

**Comment by trentmc** [comment]
Branch: https://github.com/oceanprotocol/ocean.py/tree/issue185-barge-n-imported

**Comment by trentmc** [comment]
Here's a flow that _did_ work. Main fix: it knew where to look for address files, because the config.ini specified them.

**Run the services.** In a new console:
```console
#grab repo
git clone https://github.com/oceanprotocol/barge
cd barge

#clean up old containers (to be sure)
docker system prune -a --volumes

#run barge with provider on
./start_ocean.sh  --with-provider2
```

**Create config.ini file.**
Create a file called `config.ini` and fill it as follows. Note that `ganache` value does _not_ have quotes around it (that would cause errors).
```
[eth-network]
network = ganache
artifacts.path = ~/.ocean/ocean-contracts/artifacts
address.file = ~/.ocean/ocean-contracts/artifacts/address.json
```

**Install the library; set envvars.** In a new console:
```console
#Initialize virtual environment and activate it.
python -m venv venv
source venv/bin/activate

#Install the ocean.py library
pip install ocean-lib

#set envvars
export TEST_PRIVATE_KEY1=0xc594c6e5def4bab63ac29eed19a134c130388f74f019bc74b8f4389df2837a58

#go into python
python
```

**Publish datatokens.** Within the py console:
```python
import os
from ocean_lib.config import Config # !!NEW!!
from ocean_lib.ocean.ocean import Ocean
from ocean_lib.web3_internal.wallet import Wallet

private_key = os.getenv('TEST_PRIVATE_KEY1')
config = Config('config.ini') # !!NEW!!
ocean = Ocean(config)

print("create wallet: begin")
wallet = Wallet(ocean.web3, private_key=private_key)
print(f"create wallet: done. Its address is {wallet.address}")

print("create datatoken: begin.")
datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet) 
print(f"created datatoken: done. Its address is {datatoken.address}")
```

**Comment by trentmc** [comment]
Also what doesn't work, is like the above comment except:

When setting envvars, also have:
```console
export CONFIG_FILE=config.ini
```

In python console, value of `config` variable uses what's supposed to be a default looking at CONFIG_FILE:
```python
config = Config('config.ini') # looks at CONFIG_FILE.  !NEW!
```

**Comment by trentmc** [comment]
Heres's how to reproduce the above buy in an ocean.py clone (rather than imported ocean.py)

### 1.2 Do Install

(like developers.md)

In a console:

```console
#clone the repo and enter into it
git clone https://github.com/oceanprotocol/ocean.py
cd ocean.py

#Install OS dependencies
sudo apt-get install -y python3-dev gcc python-pytest

#Initialize virtual environment and activate it.
python -m venv venv
source venv/bin/activate

#Install modules in the environment.
pip install -r requirements_dev.txt
```

## 2. Run the services

(like developers.md)

Use Ocean Barge to run local Ethereum node with Ocean contracts, Aquarius, and Provider.

In a new console:

```console
#grab repo
git clone https://github.com/oceanprotocol/barge
cd barge

#clean up old containers (to be sure)
docker system prune -a --volumes

#run barge with provider on
./start_ocean.sh  --with-provider2
```

## 3. Set up contracts

(Like developers.md, except (a) do _not_ set CONFIG_FILE envvar; (b) unstead, set NETWORK_URL)

In console:

```console
#specify config file as an envvar
export NETWORK_URL=ganache

#set private keys of two accounts
export TEST_PRIVATE_KEY1=0xc594c6e5def4bab63ac29eed19a134c130388f74f019bc74b8f4389df2837a58
export TEST_PRIVATE_KEY2=0xef4b441145c1d0f3b4bc6d61d29f5c6e502359481152f869247c7a4244d45209

#deploy new OCEAN token; update ~/.ocean/ocean-contracts/artifacts/address.json; send OCEAN to accounts
./deploy.py ganache
```

## 4. Test

Like quickstart.

In python console:
```python
import os
from ocean_lib.ocean.ocean import Ocean
from ocean_lib.web3_internal.wallet import Wallet

private_key = os.getenv('TEST_PRIVATE_KEY1')
config = {'network': os.getenv('NETWORK_URL')}
ocean = Ocean(config)

print("create wallet: begin")
wallet = Wallet(ocean.web3, private_key=private_key)
print(f"create wallet: done. Its address is {wallet.address}")

print("create datatoken: begin.")
datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet) 
```

The last line will fail with the same traceback as observed from imported ocean.py.
```console
>>> datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet) 
WARNING:root:No logs were found for tx 0x3cf87d8c35608e36fcc9f09e4a2ff7b61e735aaac3e5edc799c18ba60398c3af.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 154, in create_data_token
    return DataToken(dtfactory.get_token_address(tx_id))
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/contract_base.py", line 50, in __init__
    self.contract_concise = ContractHandler.get_concise_contract(self.name, address)
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/contract_handler.py", line 83, in get_concise_contract
    return ContractHandler._get(name, address)[1]
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/contract_handler.py", line 59, in _get
    return ContractHandler._contracts.get(name) or ContractHandler._load(
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/contract_handler.py", line 146, in _load
    return ContractHandler._contracts[(contract_name, address)]
KeyError: ('DataTokenTemplate', '')
```

**Comment by trentmc** [comment]
This PR https://github.com/oceanprotocol/ocean.py/pull/222 is a step towards solving this issue. 

I will revisit _this_ issue after the following get addressed: mutl-repo-issue#83, #202, #227. After those, _this_ issue may be super simple.

**Comment by trentmc** [comment]
Note: in the previous commit https://github.com/oceanprotocol/ocean.py/commit/57c6f580a1bb9adf237b82abab3a20d65ebfc1fa, in `ocean.py::Ocean.create_data_token()`, there's now an assert as soon as the datatoken is created. This catches the error sooner.
```python
address = dtfactory.get_token_address(tx_id)
assert address, "new datatoken has no address"
dt = DataToken(address)
return dt
```

**Comment by trentmc** [comment]
Here's the fundamental problem:

It simply doesn't see addresses, because it was never told where `address.json` is. 

We gave it a config, but the config was incomplete. It would have tried to fill in, then it would have failed.

Which means _this_ issue is now simply redundant with #205. 

Therefore, closing _this_ issue.
