### ISSUE TITLE
create_data_token() fail when using default CONFIG_FILE value, looks like artifacts issue

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#205]
**Describe the bug**

The following configuration fails:
- using barge
- import ocean.py (vs git clone)
- a config.ini file that includes location of  addresses artifacts is _not_ specified
- exported CONFIG_FILE ennvar as config.ini
- in py code, do _not_ specify the location of config file (it's supposed to use CONFIG_FILE envvar)
- trying to do simple quickstart functionality 

Error: 
```console
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 157, in create_data_token
    assert address, "new datatoken has no address"
```

**To Reproduce**

1. Do initial steps in developers.md to install dependencies, run the services, set up contracts

2. In console:
```console
export CONFIG_FILE=config.ini
```

(This is actually done as part of "set up contracts", but putting here just to make it obvious that it was set.)

3. In python console:

```python
import os
from ocean_lib.config import Config
from ocean_lib.ocean.ocean import Ocean
from ocean_lib.web3_internal.wallet import Wallet

private_key = os.getenv('TEST_PRIVATE_KEY1')
config = Config() # note how no config file is specified. In this case, it uses CONFIG_FILE envvar
ocean = Ocean(config)

print("create wallet: begin")
wallet = Wallet(ocean.web3, private_key=private_key)
print(f"create wallet: done. Its address is {wallet.address}")

print("create datatoken: begin.")
datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet) 
```

The last line will fail. Traceback is below.

Note: it _does_ pass if the filename is explicitly stated. 

**Expected behavior**
The last line not to fail. While all pytest tests still passing.

Related: 
- #268 "Aquarius + tox crashes, looks like ocean.py artifacts issue"
- #185 "create_data_token() fail when addresses not specified, looks like artifacts issue" -- failed with the same error, with a different envvar setup (it didn't use config.ini, _this_ issue does)
- [multi-repo#83](https://github.com/oceanprotocol/multi-repo-issue/issues/83) "ocean-contracts is hard to use in python, including in ocean.py"

**Config.ini contents**
For reference, here is part of the config.ini file. 
```text
[eth-network]
network = ganache
artifacts.path = ~/.ocean/ocean-contracts/artifacts
address.file = ~/.ocean/ocean-contracts/artifacts/address.json
```

`artifacts.path` and `address.file` are the defaults for barge.

**Traceback**

```console
>>> datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet) 
WARNING:root:No logs were found for tx 0x47c1f5e6096eb2d9a5cce8f7cd086b736b570ff5a3c576c4055579ec90df693d.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 157, in create_data_token
    assert address, "new datatoken has no address"
AssertionError: new datatoken has no address
```

**Comment by trentmc** [comment]
Update: I just tried to reproduce it again. It now fails earlier, before even getting to the error reported in the description.

In step 3, in Python console, I make it to the following line.
```python
import os
from ocean_lib.config import Config
from ocean_lib.ocean.ocean import Ocean
```
>>> from ocean_lib.ocean.ocean import Ocean
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 13, in <module>
    from ocean_lib.data_provider.data_service_provider import DataServiceProvider
  File "/home/trentmc/code/ocean.py/ocean_lib/data_provider/data_service_provider.py", line 19, in <module>
    from ocean_lib.web3_internal.utils import add_ethereum_prefix_and_hash_msg
  File "/home/trentmc/code/ocean.py/ocean_lib/web3_internal/utils.py", line 85, in <module>
    def privateKeyToAddress(private_key: str) -> str:
  File "/home/trentmc/code/ocean.py/ocean_lib/enforce_typing_shim.py", line 18, in enforce_types_shim
    if not ConfigProvider.get_config()["util"].getboolean("typecheck"):
  File "/home/trentmc/code/ocean.py/ocean_lib/config_provider.py", line 17, in get_config
    raise AssertionError("set_config first.")
AssertionError: set_config first.
```

I will report this as a new issue.
