### ISSUE TITLE
Base 18 conversions

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#231]
There are currently inconsistencies in the handling of large integers. Smart contracts use big integer number representation and multiply a number with 10^18 in order to properly represent it. Ocean.py is inconsistent in dealing with this representation, sometimes showing end-users the "long" number and internally using the short version etc.

**Solution**
Everything related to internals should be handled in the "long" format.
Everything related to GUIs should be handled in the "short" format (aka normal numbers 😅 )

**Discussion and additional context**
- We need to identify and fix where each format is appropriate throughout the application.
- An example: in the models/data_token.py file, requesting `get_info` will return a dictionary. One of its keys is `totalSupply`, with a value of x. This makes me think there are x tokens. However, running the `totalSupply` function directly will return x * 10^18. This makes me think I have many more tokens than x. And if I don't check the value to *actually see* that something is wrong, I might perform operations on them, and the result will be wrong.

**Comment by trentmc** [comment]
Yes x 10.

What can help as a step towards this: 
- revive dynamic type checking (#37) 
- then aggressively add in type hints on all values passed relating to OCEAN, ETH and datatokens. The "long" format (base 18) is always an int, and "short format" is always a float. This will weed out issues.

Also what can help as a step towards this:
- Fix ocean.py "data_token.py ERC20 functionality doesn't reflect ERC20 interface" #228. This includes deprecating `get_info()`, since it doesn't follow ERC20 interface and it's poor OO interface design.

**Comment by trentmc** [comment]
Put into V4, since this is breaking changes to the interface.

**Comment by DMats** [comment]
I created a branch for this issue: https://github.com/oceanprotocol/ocean.py/tree/issue231-reduce-type-conversions

**Comment by DMats** [comment]
# Proposed Changes

## Stop using "base 18" terminology
We should stop using the term "base 18". In computing, "base X" denotes the number of possible values for any given digit, not precision.

## Use `decimal.Decimal` instead of `float`
>The "long" format is always an int, and "short format" is always a float.

Instead of `float`, I propose we use a more precise alternative: [`decimal.Decimal`](https://docs.python.org/3/library/decimal.html)

>* Decimal numbers can be represented exactly. In contrast, numbers like 1.1 and 2.2 do not have exact representations in binary floating point. End users typically would not expect 1.1 + 2.2 to display as 3.3000000000000003 as it does with binary floating point.
>* The exactness carries over into arithmetic. In decimal floating point, 0.1 + 0.1 + 0.1 - 0.3 is exactly equal to zero. In binary floating point, the result is 5.5511151231257827e-017. While near to zero, the differences prevent reliable equality testing and differences can accumulate. For this reason, decimal is preferred in accounting applications which have strict equality invariants.

## Conventions

1. All internal token amounts should be type `int` denoted in Wei. Ethereum uses a 256 word size so if the underlying smart contract uses `uint`, enforce `MAX_UINT256 = 2 ** 256 - 1` and if the underlying smart contract uses `int`, enforce `MAX_INT256 = 2 ** 255 - 1` and `MIN_INT256 = 2 ** 255 * -1`.
3. All human-readable token amounts should be type `Decimal` denoted in Ether (the unit, not the currency). In other words, they should be quantized to 18 decimal places using bankers rounding
2. All variables used in token calculations should be type `int` or `Decimal` denoted in Wei or without units. For example, fee rates, datatoken cap, and OCEAN cap should be `int`; fee percentages should be `Decimal`.

    1. When an `int` and a `Decimal` are combined, the result is a `Decimal` regardless of the operand order.
    2. After all calculations are complete, [round](https://github.com/python/cpython/blob/3.9/Lib/_pydecimal.py#L1830) the result which uses bankers rounding to eliminate the fractional part.

    ```python
    >>> from decimal import Decimal
    >>> amount_in_wei = 123456789123456789
    >>> fee_percentage = Decimal('0.001') # 0.1%
    >>> fee_in_wei_unrounded = amount_in_wei * fee_percentage
    >>> fee_in_wei_unrounded
    Decimal('123456789123456.789')
    >>> fee_in_wei = round(fee_in_wei_unrounded)
    >>> fee_in_wei
    123456789123457
    ```

4. Use `Web3.fromWei()` to convert from Wei to Ether. This enforces the `MAX_UINT256` limit, so the result is guaranteed to have 18 digits of precision or less.

    ```python
    >>> from web3 import Web3
    >>> MAX_UINT256 = 2 ** 256 - 1
    >>> Web3.fromWei(MAX_UINT256 + 1, 'ether')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/david/projects/ocean.py/venv/lib/python3.8/site-packages/eth_utils/currency.py", line 52, in from_wei
        raise ValueError("value must be between 1 and 2**256 - 1")
    ValueError: value must be between 1 and 2**256 - 1
    ```
5. Use `Web3.toWei(amount.quantize(PRECISION_18))` to convert from Ether to Wei. quantize is required because `Web3.toWei()` truncates instead of rounding, as evidenced below:

    ```python
    # Demonstration how to use quantize
    >>> from decimal import Decimal
    >>> from web3 import Web3
    >>> PRECISION_18 = Decimal(10) ** -18
    >>> raw_user_input = '0.123456789123456789777' # 21 digits of precision, trailing `777` should be rounded away
    >>> quantized_user_input = Decimal(raw_user_input).quantize(PRECISION_18)
    >>> quantized_user_input
    Decimal('0.123456789123456790')
    >>> user_input_in_wei = Web3.toWei(quantized_user_input, 'ether')
    123456789123456790

    # `Web3.toWei()` truncates instead of rounding
    >>> raw_user_input = '0.123456789123456789777'
    >>> user_input = Web3.toWei(raw_user_input, 'ether')
    >>> user_input
    123456789123456789
    ```

4. Time amounts should be type `int` expressed in a unit that makes sense given the context (commonly milliseconds or seconds).
5. Block numbers should be type `int`.
6. If an external API requires `float` denoted in Ether, quantize to 18 digits of precision and coerce to `float`.

    ```python
    >>> from decimal import Decimal
    >>> PRECISION_18 = Decimal(10) ** -18
    >>> float(Decimal(0.123456789123456789777).quantize(PRECISION_18))
    0.12345678912345678
    ```

## Context
The default context specifies 28 digits of precision and ROUND_HALF_EVEN (bankers rounding), and a few sensible exception traps, so it does not need to be changed.

```python
>>> from decimal import getcontext
>>> getcontext()
Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999, Emax=999999, capitals=1, clamp=0, flags=[], traps=[InvalidOperation, DivisionByZero, Overflow])
```

# Remove `to_base()`, `to_base_18()`, `from_base()`, and `from_base_18()`
The names of these functions are misleading and Web3.py provides a standard alternative: `Web3.toWei()` and `Web3.fromWei()`.

# `2 ** 255` is not the maximum value of `uint256` nor `int256`

There are places in `ocean.py` that incorrectly specify `2 ** 255` as the max value.

```python
MAX_UINT256 = 2 ** 256 - 1
MAX_INT256 = 2 ** 255 - 1
MIN_INT256 = 2 ** 255 * -1
```

**Comment by trentmc** [comment]
I appreciate the thoroughness and thoughtfulness of these recommendations.

I reviewed each specific recommendation. I am fine with all of them.

Some notes:
- Q: does web3.py use a Decimal approach? A: Yes. E.g. `web3.fromWei()` also returns Decimals. 
- The historical reason for `base18` is the following. Chronologically: We considered other # decimals for datatokens, eg even 0 decimals. Then, early code used built-in python function `pow()` where `base` was one of the arguments. Then we introduced shortcut functions that set `base=18` without needing to be an argument. Those functions were named `to_base_18`, `from_base_18`. We didn't bother converting to use to/from Wei functions, with the argument that Wei is really just for Ether. And here we are. 
- Since then, it's obvious that `base=18` always. And using to/from Wei functions simplifies our codebase (and arguably is easier to understand anyway). And finally we have more people working on ocean.py including fixing things like this. So the historical reasons fade away:)

**Comment by DMats** [comment]
@calina-c @trentmc 

I have a few questions aimed at better defining the scope of this task.

1. Is ocean.py the appropriate place to convert from Wei to Ether? Or does it make more sense to push this responsibility to the GUIs? I figured I'd ask because if the responsibility can be pushed elsewhere, ocean.py would only need to deal with Wei (ints).

*The rest of the questions assume that ocean.py is the appropriate place to convert Wei to Ether*

2. How do I determine which methods supply data that is destined for a GUI? I'm looking for a useful heuristic like "it's a GUI method if it's in file X.py" or "it's a GUI method if it is used by X external codebase".

3. Which classes or functions in ocean.py are considered part of the semantically versioned API? (Corollary: Which classes or functions are considered "internal" and can have their APIs broken without affecting the version number?)

4. Anytime ocean.py provides a method that returns human-readable Ether values, should it also offer a method that returns Wei values? 

5. the Same question as (4) but reversed.

**Comment by trentmc** [comment]
> Is ocean.py the appropriate place to convert from Wei to Ether? Or does it make more sense to push this responsibility to the GUIs?

The latter. ocean.py should only deal with Wei.

That's the basis of this whole ticket. As the description says:
"Everything related to internals should be handled in the "long" format [Wei]. Everything related to GUIs should be handled in the "short" format (aka normal numbers 😅 ) [Eth]"

Ocean.py READMEs and unit tests will need to do Eth->Wei conversions.

> The rest of the questions assume that ocean.py is the appropriate place to convert Wei to Ether

As discussed above, ocean.py is _not_ the appropriate place. The questions highlight the problem with dividing! Hence the point of this issue.

**Comment by DMats** [comment]
Thanks for clearing that up! I'm glad I asked. So in broad strokes, I will:

1. Transform all ocean.py APIs to denote values in Wei (for both parameters and return values).
2. Update READMEs and unit tests to denote values in Ether and perform conversions whenever they interact with ocean.py

**Comment by trentmc** [comment]
Yep!

**Comment by DMats** [comment]
@trentmc We've already agreed that this issue can and will break the ocean.py API. 

I recommend creating a multi-repo EPIC to track the changes in repos that depend on this one like aquarius and provider.

Does the scope of my current assignment extend to the repos that depend on ocean.py?

**Comment by trentmc** [comment]
Yes.

**Comment by DMats** [comment]
>I recommend creating a multi-repo EPIC to track the changes in repos that depend on this one like aquarius and provider.

I've changed my mind regarding the recommendation in my last comment: I just remembered it's possible to link an issue with a PR from another repository (at least in ZenHub it's possible, not sure about Github). So an EPIC isn't the right choice. I think it's better to just keep this as the main issue, and link the PRs from Aquarius and Provider to this issue.

**Comment by DMats** [comment]
In a recent daily stand-up, I made a case for using half even rounding but ultimately the team decided to round down via truncation in all cases where rounding occurs, including:

1. Result of percentage calculations (especially when removing a % of tokens from a pool or when calculating fees)
2. When displaying balances
3. When a user inputs a value with too many digits of precision

**Comment by DMats** [comment]
@trentmc @alexcos20 @calina-c 
Should errors, warnings, and other log messages denote token amounts in wei or ether? I see pros and cons to both approaches. Whichever we choose, I think we should try to be consistent across all of ocean.py.

**Comment by trentmc** [comment]
Or both. Benefit is that it's human readable and easy to debug.

**Comment by DMats** [comment]
Fair point.  Okay, for errors, warnings, logs, and other prints I'll denote token amounts in both wei and ether.  Something like

`
Error: Insufficient balance. User requested 123456789123456789 wei (0.123456789123456789 ether) but only 5 wei (0.000000000000000005 ether) available.
`

**Comment by trentmc** [comment]
Looks fine to me.

**Comment by trentmc** [comment]
You could create a special string creation utility to make it easy.

See the last two methods here:
https://github.com/oceanprotocol/tokenspice2/blob/master/util/strutil.py

**Comment by DMats** [comment]
@trentmc Sure, I'll create some utilities. The ones I create will account for the different conventions between fiat and tokens. And they'll use Decimal instead of float.

**Comment by DMats** [comment]
I finished adding a couple of utilities:

1. `pretty_ether` makes token amounts denoted in ether human-readable by shortening them and adding well known scaling symbols and an optional ticker symbol

For example:
```python
pretty_ether("1234", ticker="OCEAN") == "1.23K OCEAN"
pretty_ether("12345678") == "12.3M"
pretty_ether("1000000000.000") == "1B"
```

2. `ether_fmt` makes token amounts denoted in ether human-readable by adding commas and adding a fixed number of decimal places and optional ticker symbol.

For example:
```python
ether_fmt("1234", ticker="OCEAN") == "1,234.000000000000000000 OCEAN"
ether_fmt("12345678", places=4) == "12,345,678.0000"
```

**Comment by DMats** [comment]
A few conclusions from today's backend sprint planning meeting:

1. This issue can focus on ocean.py.  New issues will be created for provider and aqarius.
2. Since this issue will cause API breaking changes, it should not be merged directly to `main`, but rather merged into a separate long-running branch (similar to what @calina-c  did with `stable-aqua` in Aquarius)

(2) is a very good thing - it allows me to start creating intermediate PRs instead of waiting until the very end to merge to `main`.

**Comment by DMats** [comment]
@trent asked that I consider submitting a PR to eth-utils to add the `pretty_ether` utility I created. https://github.com/ethereum/eth-utils (If I can do it in a way where it doesn't bottleneck us elsewhere).

**Comment by DMats** [comment]
I've assigned a remaining time estimate of 21 half days to this task.

My reasoning is that I'll need at least another week to finish all the code changes and then I suspect the review will take longer than normal.

**Comment by DMats** [comment]
PR #281 has been reviewed and merged to the `wei-interface` branch. :tada: I'm glad to have a 2nd pair of eyes on the work I've done so far. A

It updated the existing to/from wei utilities to use Decimal instead of float and generally laid the groundwork for eliminating conversions. ll of the unit tests pass with a few minor hacks to deal with incorrect math due to limitations of the floating-point data type.

However, I would not consider this issue complete because many of the APIs still contain float parameters so the internal logic still converts from float to Decimal and then from ether to wei.

So, I am moving this issue to the backlog and hope to pick it up in a future sprint.

**Comment by DMats** [comment]
I synced the `wei-interface` branch with `main` and intend to continue working on this task this week.
