### ISSUE TITLE
DataTokenTemplate address undefined in ocean.py quickstart simple workflow

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#234]
I got a KeyError while running the ocean.py quickstart simple workflow. I suspect that I'm missing an env variable.

Python output

```
(venv) david@david-Inspiron-5502:~/projects/barge$ echo $TEST_PRIVATE_KEY1 
0xc594c6e5def4bab63ac29eed19a134c130388f74f019bc74b8f4389df2837a58
(venv) david@david-Inspiron-5502:~/projects/barge$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from ocean_lib.config import Config
>>> from ocean_lib.ocean.ocean import Ocean
>>> from ocean_lib.web3_internal.wallet import Wallet
>>> private_key = os.getenv('TEST_PRIVATE_KEY1')
>>> config = Config('config.ini')
>>> ocean = Ocean(config)
>>> print("create wallet: begin")
create wallet: begin
>>> wallet = Wallet(ocean.web3, private_key=private_key)
>>> print(f"create wallet: done. Its address is {wallet.address}")
create wallet: done. Its address is 0xe2DD09d719Da89e5a3D0F2549c7E24566e947260
>>> print("create datatoken: begin.")
create datatoken: begin.
>>> datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet) 
WARNING:root:No logs were found for tx 0xa4c0e354606fe330aed9f8b252b42384deb755a7f679e27be926b81661a0c4ff.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean.py", line 154, in create_data_token
    return DataToken(dtfactory.get_token_address(tx_id))
  File "/home/david/venv/lib/python3.8/site-packages/ocean_lib/web3_internal/contract_base.py", line 50, in __init__
    self.contract_concise = ContractHandler.get_concise_contract(self.name, address)
  File "/home/david/venv/lib/python3.8/site-packages/ocean_lib/web3_internal/contract_handler.py", line 83, in get_concise_contract
    return ContractHandler._get(name, address)[1]
  File "/home/david/venv/lib/python3.8/site-packages/ocean_lib/web3_internal/contract_handler.py", line 59, in _get
    return ContractHandler._contracts.get(name) or ContractHandler._load(
  File "/home/david/venv/lib/python3.8/site-packages/ocean_lib/web3_internal/contract_handler.py", line 146, in _load
    return ContractHandler._contracts[(contract_name, address)]
KeyError: ('DataTokenTemplate', '')
>>> print(f"created datatoken: done. Its address is {datatoken.address}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'datatoken' is not defined
```

Barge output:

```
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | net_version
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | net_version
ganache_1          | eth_estimateGas
ganache_1          | eth_getTransactionCount
ganache_1          | eth_gasPrice
ganache_1          | eth_gasPrice
ganache_1          | eth_sendRawTransaction
ganache_1          | 
ganache_1          |   Transaction: 0xa4c0e354606fe330aed9f8b252b42384deb755a7f679e27be926b81661a0c4ff
ganache_1          |   Gas usage: 22728
ganache_1          |   Block Number: 11
ganache_1          |   Block Time: Wed Mar 17 2021 22:10:02 GMT+0000 (Coordinated Universal Time)
ganache_1          | 
ganache_1          | eth_getTransactionReceipt
ganache_1          | eth_getTransactionReceipt
ganache_1          | eth_getTransactionReceipt
ganache_1          | eth_blockNumber
aquarius_1         | 2021-03-17 22:10:08,281 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:10, current_block:11 <<<<
aquarius_1         | 2021-03-17 22:10:08,281 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataCreated, 10, 11)..
ganache_1          | eth_newFilter
ganache_1          | eth_getFilterLogs
aquarius_1         | 2021-03-17 22:10:08,295 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 10, 11)..
ganache_1          | eth_newFilter
ganache_1          | eth_getFilterLogs
ganache_1          | eth_blockNumber
aquarius_1         | 2021-03-17 22:10:09,130 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:10, current_block:11 <<<<
ganache_1          | eth_getLogs
ganache_1          | eth_getLogs
ganache_1          | eth_getLogs
ganache_1          | eth_getLogs
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
<snip>
```

**Comment by DMats** [comment]
When I install `ocean-lib` inside my venv, the `address.json` file is installed at `venv/artifacts/address.json`

Thus, I think the simple workflow instructions should be edited like so (minus the backslashes '\'):

```
## Create config file

Create a file called `config.ini` and fill it as follows.

\```text
[eth-network]
network = ganache
artifacts.path = path/to/venv/artifacts
address.file = path/to/venv/artifacts/address.json
\```
```

**Comment by trentmc** [comment]
I just deleted my barge, deleted `~/.ocean`, and went through the whole quickstart README flow. It worked for me.

You shouldn't have to get it to point to `path/to/venv/artifacts` because running barge should populate `~/.ocean/ocean-contracts/artifacts`.

To proceed: do you have a `~/.ocean` directory? If not, try re-doing the barge part of the README. Then, do you? 

For convenience, here's the barge part of the README:

In a new console:
```console
#grab repo
git clone https://github.com/oceanprotocol/barge
cd barge

#clean up old containers (to be sure)
docker system prune -a --volumes

#run barge (runs ganache, Provider, Aquarius)
./start_ocean.sh  --with-provider2
```

**Comment by DMats** [comment]
@trentmc I deleted barge and double-checked that I didn't have `~/.ocean` directory. I then re-ran the barge part of the README. There were no errors in the `start_ocean.sh` output and the warnings seemed innocuous. Yet, once it settled, I did not have an `~/.ocean` directory.

I've attached my [start_ocean.sh output](https://app.zenhub.com/files/266274883/548889b2-d452-4389-a911-e9dd5937ff47/download) for review.

**Comment by trentmc** [comment]
Thanks for the info.

As an aside, we have the following related github issues: #185 and #205 raise a similar error but for different configurations. And [multi-repo#83](https://github.com/oceanprotocol/multi-repo-issue/issues/83) is to get a better location for the addresses.

However for your issue, it really should be using the `~/.ocean` directory. At least according to my understanding of barge. Let's check with Alex. See my next comment...

**Comment by trentmc** [comment]
@alexcos20 I have a Q for you: when barge is run, ie via `./start_ocean.sh  --with-provider2`, does it auto create the `~/.ocean directory`?

**Comment by trentmc** [comment]
I just double-checked to see if barge auto-creates the `~/.ocean` directory, as follows.

1. delete `barge` directory
2. move old `~/.ocean` directory to `~/.ocean-old`
3. `cd; ls -lsart`. This shows the contents of the directory with most recent changes at the bottom. It shouldn't display `./ocean` of course
4. open a different console, and re-get barge going:

```console
#grab repo
git clone https://github.com/oceanprotocol/barge
cd barge

#clean up old containers (to be sure)
docker system prune -a --volumes

#run barge (runs ganache, Provider, Aquarius)
./start_ocean.sh  --with-provider2
```

5. In original console: `cd; ls -lsart`. It should now display `./ocean`, as the most recent thing. That is, barge auto created the ocean directory.


@DMats maybe you could try doing the above steps too. Please let me know if barge successfully auto created the ocean directory.

**Comment by DMats** [comment]
Sure. I'll do this now and record the results here when I'm done.

**Comment by DMats** [comment]
@trentmc barge does not create the `~/.ocean` directory.

```
david@david-Inspiron-5502:~$ rm -rf projects/barge/
david@david-Inspiron-5502:~$ ll projects/barge/
ls: cannot access 'projects/barge/': No such file or directory
david@david-Inspiron-5502:~$ mv ~/.ocean ~/.ocean-old
mv: cannot stat '/home/david/.ocean': No such file or directory
david@david-Inspiron-5502:~$ cd; ls -lsart
total 264
 4 drwxr-xr-x  3 root  root   4096 Mar 15 23:54  ..
 4 -rw-r--r--  1 david david  3771 Mar 15 23:54  .bashrc
 4 -rw-r--r--  1 david david   220 Mar 15 23:54  .bash_logout
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Videos
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Templates
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Public
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Music
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Documents
 4 drwx------  5 david david  4096 Mar 16 18:10  .mozilla
 4 drwxrwxr-x  3 david david  4096 Mar 16 18:26  .vscode-oss
 4 drwx------  3 david david  4096 Mar 16 18:26  .pki
 0 -rw-r--r--  1 david david     0 Mar 17 11:21  .sudo_as_admin_successful
64 -rw-rw-r--  1 david david 61530 Mar 17 12:19  david.jpg
 4 drwxr-xr-x  2 david david  4096 Mar 17 12:28  Desktop
 4 drwx------  3 david david  4096 Mar 17 12:44  .sane
 4 drwxrwxr-x  3 david david  4096 Mar 17 14:08  installers
 4 drwxr-xr-x  2 david david  4096 Mar 17 14:41  .hplip
 4 drwx------  7 david david  4096 Mar 17 15:22  .zoom
 4 drwxr-xr-x  2 david david  4096 Mar 17 16:53  Downloads
 4 -rw-rw-r--  1 david david   337 Mar 17 17:11  .gitconfig
 4 drwxr-xr-x 10 david david  4096 Mar 17 17:27  snap
 4 -rw-r--r--  1 david david   808 Mar 17 17:49  .profile
 4 drwxr-xr-x  5 david david  4096 Mar 17 17:57  .local
 4 drwxrwxr-x  7 david david  4096 Mar 17 18:02  venv
 4 drwx------  2 david david  4096 Mar 17 18:25  .ssh
 4 -rw-------  1 david david   783 Mar 17 18:53  .python_history
12 -rw-------  1 david david  8379 Mar 17 19:02  .viminfo
60 -rw-rw-r--  1 david david 61317 Mar 18 09:26 'start_ocean.sh output - .ocean dir not created.txt'
 4 drwxr-xr-x 25 david david  4096 Mar 18 09:26  .
 4 drwxrwxr-x 21 david david  4096 Mar 18 09:34  .cache
 4 drwxr-xr-x  2 david david  4096 Mar 18 09:41  Pictures
 4 drwx------ 22 david david  4096 Mar 18 10:39  .config
 8 -rw-------  1 david david  5531 Mar 18 10:48  .bash_history
 4 drwx------  3 david david  4096 Mar 18 10:54  .gnupg
 4 drwxrwxr-x  3 david david  4096 Mar 18 12:05  projects
david@david-Inspiron-5502:~$ cd; ls -lsart
total 264
 4 drwxr-xr-x  3 root  root   4096 Mar 15 23:54  ..
 4 -rw-r--r--  1 david david  3771 Mar 15 23:54  .bashrc
 4 -rw-r--r--  1 david david   220 Mar 15 23:54  .bash_logout
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Videos
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Templates
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Public
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Music
 4 drwxr-xr-x  2 david david  4096 Mar 16 00:02  Documents
 4 drwx------  5 david david  4096 Mar 16 18:10  .mozilla
 4 drwxrwxr-x  3 david david  4096 Mar 16 18:26  .vscode-oss
 4 drwx------  3 david david  4096 Mar 16 18:26  .pki
 0 -rw-r--r--  1 david david     0 Mar 17 11:21  .sudo_as_admin_successful
64 -rw-rw-r--  1 david david 61530 Mar 17 12:19  david.jpg
 4 drwxr-xr-x  2 david david  4096 Mar 17 12:28  Desktop
 4 drwx------  3 david david  4096 Mar 17 12:44  .sane
 4 drwxrwxr-x  3 david david  4096 Mar 17 14:08  installers
 4 drwxr-xr-x  2 david david  4096 Mar 17 14:41  .hplip
 4 drwx------  7 david david  4096 Mar 17 15:22  .zoom
 4 drwxr-xr-x  2 david david  4096 Mar 17 16:53  Downloads
 4 -rw-rw-r--  1 david david   337 Mar 17 17:11  .gitconfig
 4 drwxr-xr-x 10 david david  4096 Mar 17 17:27  snap
 4 -rw-r--r--  1 david david   808 Mar 17 17:49  .profile
 4 drwxr-xr-x  5 david david  4096 Mar 17 17:57  .local
 4 drwxrwxr-x  7 david david  4096 Mar 17 18:02  venv
 4 drwx------  2 david david  4096 Mar 17 18:25  .ssh
 4 -rw-------  1 david david   783 Mar 17 18:53  .python_history
12 -rw-------  1 david david  8379 Mar 17 19:02  .viminfo
60 -rw-rw-r--  1 david david 61317 Mar 18 09:26 'start_ocean.sh output - .ocean dir not created.txt'
 4 drwxr-xr-x 25 david david  4096 Mar 18 09:26  .
 4 drwxrwxr-x 21 david david  4096 Mar 18 09:34  .cache
 4 drwxr-xr-x  2 david david  4096 Mar 18 09:41  Pictures
 4 drwx------ 22 david david  4096 Mar 18 10:39  .config
 8 -rw-------  1 david david  5531 Mar 18 10:48  .bash_history
 4 drwx------  3 david david  4096 Mar 18 10:54  .gnupg
 4 drwxrwxr-x  4 david david  4096 Mar 18 12:07  projects
david@david-Inspiron-5502:~$ 
```

**Comment by DMats** [comment]
Wait!  I might know what I'm doing wrong. One second, let me re-run it.

**Comment by DMats** [comment]
@trentmc 
:facepalm: I ran `sudo ./start_ocean.sh  --with-provider2` so my `.ocean` directory appeared at `/root/.ocean`. But when I run `./start_ocean.sh --with-provider2` without the `sudo` I get this error:

```
david@david-Inspiron-5502:~/projects/barge$ ./start_ocean.sh --with-provider2
export ADDRESS_FILE=/home/david/.ocean/ocean-contracts/artifacts/address.json
aquarius exists


                          Welcome to
    
                             ,-._
                           _.-'  '--.
                         .'      _  -`\_
                        / .----.`_.'----'
                        ;/     `
                       /_;
             
                    ._      ._      ._      ._
                _.-._)`\_.-._)`\_.-._)`\_.-._)`\_.-._
       ___                     ___         _               _ 
      / _ \ __ ___ __ _ _ _   | _ \_ _ ___| |_ ___  __ ___| |
     | (_) / _/ -_) _` | ' \  |  _/ '_/ _ \  _/ _ \/ _/ _ \ |
      \___/\__\___\__,_|_||_| |_| |_| \___/\__\___/\__\___/_|
                            
                               ---

                Get info: oceanprotocol.com
                Get docs: docs.oceanprotocol.com
                Get code: github.com/oceanprotocol
                Get help: discord.gg/TnXjkR5

                               ---

Starting with a 2nd Provider...

docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```

I believe I need to run the optional post-install step [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user). I didn't do this previously because I installed `docker` via the Ubuntu Software store which never prompted me to do anything after the `docker` snap was installed.

I need to log off for these changes to take effect.  I'll add the results here after I've tested again.

**Comment by DMats** [comment]
After allowing non-root users to manage docker, I was able to successfully run `./start_ocean.py --with-provider2` without `sudo`. I also observe `~/.ocean` directory is created. :raised_hands:

After that, I was able to successfully complete the ocean.py quickstart simple workflow.

```
>>> print("create datatoken: begin.")
create datatoken: begin.
>>> datatoken = ocean.create_data_token("Dataset name", "dtsymbol", from_wallet=wallet) 
>>> print(f"created datatoken: done. Its address is {datatoken.address}")
created datatoken: done. Its address is 0xDbec339392A8f8074506FDdfACCA0328bd022C15
```

**Comment by trentmc** [comment]
In the end, there was no core problem as David pointed out in the last issue.

Also as David pointed out, we could improve the README to help others as they onboard. Including explaining that docker must allow non-root users and link to instructions. I just did that in this commit:
https://github.com/oceanprotocol/ocean.py/commit/58f99df6cc524fc3e25335040578f8f6cf6ac5f0
