### ISSUE TITLE
Aquarius + tox crashes, looks like ocean.py artifacts issue

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#268]
**Describe the bug**

AlexC: looks like aqua works fine in barge, but that is because we have the artifacts exported by ocean-contracts. if we test aqua with tox (which creates address.json, but no artifacts), everything will crash.

**To Reproduce**

1. In `aquarius` repo, run `tox`

**Expected behavior**
Doesn't fail.

**Additional context**

AlexC managed to stabilize aquarius by using ocean.py version 0.5.12.  [On pypi](https://pypi.org/project/ocean-lib/) ocean.py is at version 0.5.15.

**Comment by trentmc** [comment]
More info from slack:

Calina: I've investigated it a bit. But until now we didn't test anything sensitive. So the issue only appears in one of the branches

----
Alex: we need event testing in aqua (pools, fre). that is why we didn't catch that earlier

----
Calina: here’s a branch that contains some tests: 
https://github.com/oceanprotocol/aquarius/pull/442

the tests pass on GitHub, but not locally :(

Other fishy things:
- locally, running with plain tox fails but creates an address.json file
- locally, running only test_events.py with pytest works, but only if that address.json exists (and the one created by tox is good)

----
- Alex: what version of ocean.py?
- Calina: 12
- Alex: can you bump to 15? And see  if tests are failing or passing
- Calina: sure
- Calina: doing so makes pytest fail too :smile:
- Calina: seems from type enforcement

![image](https://user-images.githubusercontent.com/5305452/114150260-21cab980-991c-11eb-8900-76a7dea35da7.png)

- David: This error means that `setup_enforce_typing_shim()` was not called before importing a file that uses the `@enforce_types_shim`

----
Alex: 
```console
# /bin/sh /aquarius/start_events_monitor.sh
default log level: 10, env var LOG_LEVEL DEBUG
2021-04-08 12:11:24 aquarius-6bb597c67f-hp5h8 __main__[266] INFO EventsMonitor: preparing
Traceback (most recent call last):
  File "./events-monitor-main.py", line 37, in <module>
    run_events_monitor()
  File "./events-monitor-main.py", line 22, in run_events_monitor
    raise AssertionError(
AssertionError: env var CONFIG_FILE is missing, make sure to set the following environment variables before starting the events monitor: ['EVENTS_RPC', 'CONFIG_FILE']
#
```
Alex: this is why aquarius fails

Marian: we have these values set in deployment:
- `name: EVENTS_RPC`
- `value: rinkeby`

Alex: and CONFIG_FILE ? what is that?

Calina: We don't have CONFIG_FILE variable set
- `CONFIG_FILE: config.ini` would this work?
- there’s a config.ini inside aquarius, root level

Marian: 
I'll try
..
no changes
```console
2021-04-08 12:16:23,239 - aquarius.config - DEBUG - Config: loading config file /aquarius/config.ini 
2021-04-08 12:16:23,239 - aquarius.config - DEBUG - Config: setting environ aquarius.url = http://0.0.0.0:5000
```
the events monitoring part is not working

----

Alex: @Marian - can you check elasticsearch ? I don't see any queries in the logs

Marian: Let me check
```console
{ 
 "name" : "elasticsearch-master-rinkeby-v3-mp-0", 
 "cluster_name" : "elasticsearch", 
 "cluster_uuid" : "GDYNmx4WS6yGzM00G9N3eg", 
 "version" : { 
   "number" : "6.6.2", 
   "build_flavor" : "default", 
   "build_type" : "tar", 
   "build_hash" : "3bd3e59", 
   "build_date" : "2019-03-06T15:16:26.864148Z", 
   "build_snapshot" : false, 
   "lucene_version" : "7.6.0", 
   "minimum_wire_compatibility_version" : "5.6.0", 
   "minimum_index_compatibility_version" : "5.0.0" 
 }, 
 "tagline" : "You Know, for Search" 
}
```

looks good

```console
{
  "cluster_name" : "elasticsearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 10,
  "active_shards" : 20,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
green
```

----

Alex: aquarius 2.2.8 up & running on rinkeby

```console
2021-04-08 13:02:53,412 - aquarius.events.metadata_updater - DEBUG - Got dt/exchanges: []
2021-04-08 13:03:04,358 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:8376886, current_block:8376887 <<<<
2021-04-08 13:03:04,358 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataCreated, 8376886, 8376887)..
2021-04-08 13:03:04,389 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 8376886, 8376887)..
2021-04-08 13:03:05,352 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:8376886, current_block:8376887 <<<<
2021-04-08 13:03:05,379 - aquarius.events.metadata_updater - DEBUG - Got pools: []
2021-04-08 13:03:05,408 - aquarius.events.metadata_updater - DEBUG - Got dt/exchanges: []
2021-04-08 13:03:26,426 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:8376887, current_block:8376888 <<<<
2021-04-08 13:03:26,427 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataCreated, 8376887, 8376888)..
2021-04-08 13:03:26,459 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 8376887, 8376888)..
2021-04-08 13:03:27,362 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:8376887, current_block:8376888 <<<<
2021-04-08 13:03:27,393 - aquarius.events.metadata_updater - DEBUG - Got pools: []
2021-04-08 13:03:27,487 - aquarius.events.metadata_updater - DEBUG - Got dt/exchanges: []
2021-04-08 13:03:38,369 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:8376888, current_block:8376889 <<<<
2021-04-08 13:03:38,370 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataCreated, 8376888, 8376889)..
2021-04-08 13:03:38,404 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 8376888, 8376889)..
2021-04-08 13:03:39,369 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:8376888, current_block:8376889 <<<<
2021-04-08 13:03:39,500 - aquarius.events.metadata_updater - DEBUG - Got pools: []
2021-04-08 13:03:39,521 - aquarius.events.metadata_updater - DEBUG - Got dt/exchanges: []
2021-04-08 13:03:50,377 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:8376889, current_block:8376890 <<<<
2021-04-08 13:03:50,377 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataCreated, 8376889, 8376890)..
2021-04-08 13:03:50,406 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 8376889, 8376890)..
2021-04-08 13:03:51,376 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:8376889, current_block:8376890 <<<<
2021-04-08 13:03:51,403 - aquarius.events.metadata_updater - DEBUG - Got pools: []
2021-04-08 13:03:51,421 - aquarius.events.metadata_updater - DEBUG - Got dt/exchanges: []
2021-04-08 13:04:12,415 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:8376890, current_block:8376891 <<<<
2021-04-08 13:04:12,415 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataCreated, 8376890, 8376891)..
2021-04-08 13:04:12,444 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 8376890, 8376891)..
2021-04-08 13:04:13,387 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:8376890, current_block:8376891 <<<<
2021-04-08 13:04:13,412 - aquarius.events.metadata_updater - DEBUG - Got pools: []
2021-04-08 13:04:13,428 - aquarius.events.metadata_updater - DEBUG - Got dt/exchanges: []
2021-04-08 13:04:24,401 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:8376891, current_block:8376892 <<<<
2021-04-08 13:04:24,401 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataCreated, 8376891, 8376892)..
2021-04-08 13:04:24,432 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 8376891, 8376892)..
2021-04-08 13:04:25,396 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:8376891, current_block:8376892 <<<<
2021-04-08 13:04:25,419 - aquarius.events.metadata_updater - DEBUG - Got pools: []
```

**Comment by trentmc** [comment]
ocean.py has a bug on using default config file: #205. That may have caused issues here. I've got a fix in a [PR](https://github.com/oceanprotocol/ocean.py/pull/272), will merge to main soon.

**Comment by calina-c** [comment]
Fixed on the stable-aqua branch, pending market deprecation of prices.
