### ISSUE TITLE
MetadataContract is showing up as None

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#452]
**Describe the bug**
I went through the simple datatokens README.

It went smoothly until the last part, in a Python step. Here's that step, and the traceback
```python
>>> ocean = Ocean(config)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/play/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean.py", line 105, in __init__
    addresses.get(MetadataContract.CONTRACT_NAME),
AttributeError: 'NoneType' object has no attribute 'get'
```

**Describe the solution**
WIP

**Comment by trentmc** [comment]
I just tried to reproduce this, from everything clean. No issues encountered. Likely what caused the issue was some older artifacts from barge.

Closing issue.
