### ISSUE TITLE
create_datatoken() fails on simplest README. Can likely fix via a new release.

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#836]
**Describe the bug**
I went through data-nfts-and-datatokens-flow.md, including installing the lib (`pip3 install --pre ocean-lib`). 

It failed with:
```text
TypeError: create_datatoken() missing 1 required positional argument: 'cap'
```

**To Reproduce**
1. Go through the data-nfts-and-datatokens-flow.md. 
2. It will fail on `create_datatoken()`. 

Note: it does _not_ fail if running from a `git clone` of ocean.py, in `v4main` branch. This means that we likely just need to 

**Expected behavior**
Don't fail.

**Likely problem, how to fix**

My guess is that we haven't released a library since [#811](https://github.com/oceanprotocol/ocean.py/issues/811) "Vesting & cap not fully removed yet". 

How to fix: release a new library. 

**Traceback**

```console
>>> erc20_token = erc721_nft.create_datatoken(
...     template_index=1, # default value
...     name="ERC20DT1",  # name for ERC20 token
...     symbol="ERC20DT1Symbol",  # symbol for ERC20 token
...     minter=alice_wallet.address,  # minter address
...     fee_manager=alice_wallet.address,  # fee manager for this ERC20 token
...     publish_market_order_fee_address=alice_wallet.address,  # publishing Market Address
...     publish_market_order_fee_token=ZERO_ADDRESS,  # publishing Market Fee Token
...     publish_market_order_fee_amount=0,
...     bytess=[b""],
...     from_wallet=alice_wallet
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/play/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
TypeError: create_datatoken() missing 1 required positional argument: 'cap'
```

**Comment by trentmc** [comment]
Please do a new release ASAP, since this is a showstopper for anyone using even the most simple ocean.py README
