### ISSUE TITLE
create_erc721_nft() gives error 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#843]
**Describe the bug / how to reproduce**

How: I went through [simple README](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/data-nfts-and-datatokens-flow.md) until the line `ocean.create_erc721_nft('NFTToken1', 'NFT1', alice_wallet)`. (This is the very first line that actually does some Ocean utility.)

Then calling it will give the following traceback.

```console
>>> ocean.create_erc721_nft('NFTToken1', 'NFT1', alice_wallet)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/ocean.py/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 164, in create_erc721_nft
    nft_factory = self.get_nft_factory()
  File "/home/trentmc/code/ocean.py/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 209, in get_nft_factory
    nft_factory_address = get_address_of_type(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/util.py", line 81, in get_address_of_type
    if address_type not in addresses.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

Note: I tried two variants of the flow:
- using `pip3 install --pre ocean-lib` as the README asks
- and using `git clone` into `v4main` branch
- and both fail

I'm also surprised that the auto-testing of READMEs didn't catch this.

**Comment by trentmc** [comment]
After @calina-c 's help digging around, this is clearly a barge problem not ocean.py problem.

To that end, I've created a barge issue: 
https://github.com/oceanprotocol/barge/issues/292

We can close _this_ issue.
