### ISSUE TITLE
Error when publishing a dataset locally

### ISSUE THREAD

**Issue by andresvsm1** [oceanprotocol/ocean.py#897]
Currently I'm trying out the ocean.py driver to test the C2D feature, but I'm not able to execute any of the [quickstart examples](https://github.com/oceanprotocol/ocean.py#-quickstart) besides the first one.

When trying to execute the [publish flow](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/publish-flow.md), I'm getting the following error:

```console
AttributeError                            Traceback (most recent call last)
/path/publish_consume.ipynb Cell 3 in <cell line: 44>()
     25 # Publish asset with services on-chain.
     26 # The download (access service) is automatically created, but you can explore other options as well
     27 
     28 # Although the execution of this cell generates an error, it creates the asset on chain
     29 asset = ocean.assets.create(
     30     metadata,
     31     publisher_wallet=wallet,
   (...)
     41     datatoken_bytess=[[b""]],
     42 )
---> 44 did = asset.did  # did contains the datatoken address
     45 print(f"did = '{did}'")

AttributeError: 'NoneType' object has no attribute 'did'
```

So I assume the call is not returning anything at all. I've read that there are some issues when trying to do some stuff locally, and maybe someone has guidelines on how to the C2D example using barge.

I'm running the following command with barge:

```console
./start_ocean.sh --no-dashboard --with-c2d
```

Everything starts correctly, or at least it seems so, but when trying to run the following code:

```py
# Create Ocean instance
from ocean_lib.example_config import ExampleConfig
from ocean_lib.ocean.ocean import Ocean
config = ExampleConfig.get_config()
ocean = Ocean(config)

# Create wallet
import os
from ocean_lib.web3_internal.wallet import Wallet
private_key = os.getenv('PRIVATE_KEY')
wallet = Wallet(ocean.web3, private_key, config.block_confirmations, config.transaction_timeout)
from ocean_lib.web3_internal.constants import ZERO_ADDRESS

# Publish an NFT token
# It is created correctly
data_nft = ocean.create_data_nft('NFTToken1', 'NFT1', wallet)
print(f"Created data NFT. Its address is {data_nft.address}")

# Specify metadata and services, using the Branin test dataset
date_created = "2021-12-28T10:55:11Z"

metadata = {
    "created": date_created,
    "updated": date_created,
    "description": "Branin dataset 2",
    "name": "Branin dataset",
    "type": "dataset",
    "author": "Trent",
    "license": "CC0: PublicDomain",
}

# ocean.py offers multiple file types, but a simple url file should be enough for this example
from ocean_lib.structures.file_objects import UrlFile
url_file = UrlFile(
    url="https://raw.githubusercontent.com/trentmc/branin/main/branin.arff"
)

# Publish asset with services on-chain.
# The download (access service) is automatically created, but you can explore other options as well

# Although the execution of this cell generates an error, it creates the asset on chain
asset = ocean.assets.create(
    metadata,
    publisher_wallet=wallet,
    files=[url_file],
    datatoken_templates=[1],
    datatoken_names=["Datatoken 1"],
    datatoken_symbols=["DT1"],
    datatoken_minters=[wallet.address],
    datatoken_fee_managers=[wallet.address],
    datatoken_publish_market_order_fee_addresses=[ZERO_ADDRESS],
    datatoken_publish_market_order_fee_tokens=[ocean.OCEAN_address],
    datatoken_publish_market_order_fee_amounts=[0],
    datatoken_bytess=[[b""]],
)

did = asset.did  # did contains the datatoken address
print(f"did = '{did}'")
```

with the following .env
```sh
# For local development with barge
# Mandatory environment variables
OCEAN_NETWORK=development
OCEAN_NETWORK_URL=http://127.0.0.1:8545/
# Use 5003 https://github.com/oceanprotocol/ocean.py/issues/89#issuecomment-1015554488
METADATA_CACHE_URI=http://127.0.0.1:5003
PROVIDER_URL=http://127.0.0.1:8030

# Replace PRIVATE_KEY if needed
PRIVATE_KEY=0xc594c6e5def4bab63ac29eed19a134c130388f74f019bc74b8f4389df2837a58
SECOND_PRIVATE_KEY=0xef4b441145c1d0f3b4bc6d61d29f5c6e502359481152f869247c7a4244d45209
# Required by Ocean.py
ADDRESS_FILE=./address.json
```

It stalls. Checking the aquarius logs, I see that it creates multiple connections and that it is trying to find a did that apparently is not registered. This problem continues for some time until it returns the error that I mention.

```console
2022-09-02 11:43:59,450 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:0640a540d598548315b3c66b6464ca694907c4ef73fdb0507986dbee4bb40f52
2022-09-02 11:43:59,455 - aquarius.app.es_instance - INFO - Asset with id did:op:0640a540d598548315b3c66b6464ca694907c4ef73fdb0507986dbee4bb40f52 was not found in ES.
2022-09-02 11:43:59,665 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:0640a540d598548315b3c66b6464ca694907c4ef73fdb0507986dbee4bb40f52
2022-09-02 11:43:59,670 - aquarius.app.es_instance - INFO - Asset with id did:op:0640a540d598548315b3c66b6464ca694907c4ef73fdb0507986dbee4bb40f52 was not found in ES.
2022-09-02 11:43:59,705 - aquarius.events.events_monitor - ERROR - Error processing MetadataCreated event: HTTPConnectionPool(host='127.0.0.1', port=8030): Max retries exceeded with url: /api/services/decrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x40171df8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
event=AttributeDict({'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0xab3b0cede36d0a90b5f08e8f9368f76f74538c248dc2231c41d00c4d44349027'), 'blockHash': HexBytes('0xafb64fc7a17cff933cc691778a4b657b334d5c7f80c1118a370e9780231ee685'), 'blockNumber': 21, 'address': '0xb38b5A1A0B7c48099a8C53dD179726bf8A416538', 'data': '0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000160ccd7f795ed1ec0fb216ef7d9cb762fdc2e71823e3509f88c57949127cfdde51a000000000000000000000000000000000000000000000000000000006311ec7600000000000000000000000000000000000000000000000000000000000000150000000000000000000000000000000000000000000000000000000000000015687474703a2f2f3132372e302e302e313a383033300000000000000000000000000000000000000000000000000000000000000000000000000000000000000103000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000451049fcc82c5abacf2c0200e8780080e82b094b57b02b72df2f19f742075efe2c00a5f357b9d85b4bae5fc52772165b9313c64422463f0d143f61ed63417013d7daf062368945a9df6e3e345f3c15764a6a0cc56ef17761cffd0e748f0fdeb9a7b47c612ced934b92673ffedcd5626c316bed25bae0078d10cebd0e602f3a6906cbc734e3f9486aba728d123daf669845c9ca9a850bc02599e3add04cbd49a4efed6cec0783230e004c0a6d2813259bafe9fb3f0cc36374840f29d7f3c81a54346f152b71323b2628ae36dcc72eda1cfaad1a7f171bfe24e57ac7fed6084c41badc624d6c58c1f5c9e8e2d009221c3407a50fff3aaba6797ce8831da2cc13232c30f70f4ad1188607a1429aa0a79df39427283d525df86ee7f4ce5d5f0488a0f839bc0105117bd1fc54434cfe233a29917f2f3f1a745a35acd0b5b160fe59158c43e83482ce26dbfa1596ac979d60ac4d9f8b6543ed71bf2a98ec90bdff17ba9777492bffaa0aedd4b79571748c5060ac50a10b85f46e33199f6b29157036b3d470e937e03b436f17e9eed9e19d7072787afc0b38ba9c8054009cbc26a3c1dae096a7e1ddcfe6e6ec1afbfc540e6694ddc9f68944f709301811ceed8be51ce7364289ecb996998b4e16ef550f8b03a6855fd0771195972f50c238a4622cdc9e1ebd421a498fab5a46450c39f7a7950d2ec55bb791ca1876dcf995d0113a5daf86d4e819b3a3b00de3f125b59d731136a90fa78b822d41a742830de2387e8cc147e0df295d4dca249d8d97e414904a3bb993f0a33fc67e575b5b116256e3efca6be3ea3ec1c2381c97c51908db239968ebdb319154eda43d1c14b262bd9738750a93b841b1459b02e957c8c8443f97e530acf6e1cda37460290b55e63b29d7838db207a1721aac3e3d49fda9dd947f61d800ccf3511fe567e7f892f1ebff892754de4e499dcd970f52a8c99381de550ffc214f67e271cfafd0eb4aa7b6b75defb51305f1d70b63b7676936b42119ad4952aa513f8bf0e90e05e6b52ccf02bd8b289fd7d4ac480be9705e5880c5fbefc2d4e9f4b0d5a69de91129b6281e5697c9c7d77c2256ec6b414a6f6050565a9dd7e8290e3889839542e88d7a216e0bbb9d51dbc0d058d9e11136d4a433ddbea10a09b9a647ff4dae7cec76a8a3ff527907bef4d334e2fe5f6bca5ae78551b9c5c6369c761ff186dba80d892b0419a8efe33690866a6fde7fbcffd650fdda01e75d41d8a282b3f724d036b2902a7c09612ce4ae5db740be901caec822fec561a94e68367bc1b52a0934b47afa6b2e0db129aa18da859442487301536ba60a30d6d81130798845f191481b568348350add417016eb663073821bb82e71a9c69f6e5a17f6e9c3d4a776fbb020a78cc7d271109d9cd33d741fe67a4383c55959d98e3af3af935f4db9b85b4c6595ab41f24e1513cc9699cd6ecfe76af157620a30cef11488a3785b8c7c0855b237766b883325b4a330a2e3534d029fc9590dd9274f1e532291b888f822c5d32045cae5128a0dbb22d89eef07d29f1e10f8f8bc20c10845857000000000000000000000000000000', 'topics': [HexBytes('0x5463569dcc320958360074a9ab27e809e8a6942c394fb151d139b5f7b4ecb1bd'), HexBytes('0x000000000000000000000000e2dd09d719da89e5a3d0f2549c7e24566e947260')], 'type': 'mined', 'removed': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1234, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1280, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1229, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 948, in send
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x40171df8e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8030): Max retries exceeded with url: /api/services/decrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x40171df8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/aquarius/aquarius/events/events_monitor.py", line 228, in handle_regular_event_processor
    event_processor.process()
  File "/aquarius/aquarius/events/processors.py", line 212, in process
    asset = decrypt_ddo(
  File "/aquarius/aquarius/events/decryptor.py", line 33, in decrypt_ddo
    response = requests.post(provider_url + "/api/services/decrypt", json=payload)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8030): Max retries exceeded with url: /api/services/decrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x40171df8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-09-02 11:43:59,717 - aquarius.events.events_monitor - INFO - Searching for MetadataUpdated events on chain 8996 in blocks 20 to 21.
2022-09-02 11:43:59,742 - aquarius.events.events_monitor - DEBUG - Searched blocks 20 to 21 on chain 89960 MetadataUpdated events detected so far.
2022-09-02 11:43:59,742 - aquarius.events.events_monitor - INFO - Finished searching for MetadataUpdated events on chain 8996 in blocks 20 to 21. 0 MetadataUpdated events detected.
2022-09-02 11:43:59,742 - aquarius.events.events_monitor - INFO - Searching for MetadataState events on chain 8996 in blocks 20 to 21.
2022-09-02 11:43:59,757 - aquarius.events.events_monitor - DEBUG - Searched blocks 20 to 21 on chain 89960 MetadataState events detected so far.
2022-09-02 11:43:59,758 - aquarius.events.events_monitor - INFO - Finished searching for MetadataState events on chain 8996 in blocks 20 to 21. 0 MetadataState events detected.
2022-09-02 11:43:59,758 - aquarius.events.events_monitor - INFO - Searching for OrderStarted events on chain 8996 in blocks 20 to 21.
2022-09-02 11:43:59,834 - aquarius.events.events_monitor - DEBUG - Searched blocks 20 to 21 on chain 89960 OrderStarted events detected so far.
2022-09-02 11:43:59,834 - aquarius.events.events_monitor - INFO - Finished searching for OrderStarted events on chain 8996 in blocks 20 to 21. 0 OrderStarted events detected.
2022-09-02 11:43:59,835 - aquarius.events.events_monitor - INFO - Searching for TokenURIUpdate events on chain 8996 in blocks 20 to 21.
2022-09-02 11:43:59,850 - aquarius.events.events_monitor - DEBUG - Searched blocks 20 to 21 on chain 89960 TokenURIUpdate events detected so far.
2022-09-02 11:43:59,851 - aquarius.events.events_monitor - INFO - Finished searching for TokenURIUpdate events on chain 8996 in blocks 20 to 21. 0 TokenURIUpdate events detected.
2022-09-02 11:43:59 8f6a54c50af3 root[74] INFO Stable connection to ES.
2022-09-02 11:43:59,883 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:0640a540d598548315b3c66b6464ca694907c4ef73fdb0507986dbee4bb40f52
2022-09-02 11:43:59,887 - aquarius.app.es_instance - INFO - Asset with id did:op:0640a540d598548315b3c66b6464ca694907c4ef73fdb0507986dbee4bb40f52 was not found in ES.
2022-09-02 11:44:00,101 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:0640a540d598548315b3c66b6464ca694907c4ef73fdb0507986dbee4bb40f52
2022-09-02 11:44:00,106 - aquarius.app.es_instance - INFO - Asset with id did:op:0640a540d598548315b3c66b6464ca694907c4ef73fdb0507986dbee4bb40f52 was not found in ES.
... -> It repeats for a while until it returns the error
```

I'm using a Mac with an M2 chip but I also tried it using a VM with Linux but the same issue appears.

**Desktop:**
 - OS: MacOS using M2 chip/ Linux  - Ubuntu 18.04.6 LTS

Running the same code on Rinkeby works fine and I was able to try some quickstart examples, but to run the C2D example, I'm not able to get anything back from the `ocean.assets.create` method

**Comment by andresvsm1** [comment]
Update: I'm still facing the same issue, but it seems like Aquarius is not reading correctly from the chain. I can see transaction events within the ganache container, but the Aquarius container doesn't have anything besides the chain id and the last block.

**Comment by andresvsm1** [comment]
Close: For some reason, Aquarius won't connect to the provider, and in order to make it work, I had to add to my `/etc/hosts` the following line `127.0.0.1    ocean_provider_1` and in my `.env`, I had to replace the `PROVIDER_URL` with `http://ocean_provider_1:8030`
