### ISSUE TITLE
Marketplace README fails because Bob has no OCEAN 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#901]
**Describe the bug**
I was going through the READMEs in sequential order. Not using ocean.py github, but installing the library (how users do it). Fresh install of barge.

Everything works fine, up until the [marketplace README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/marketplace-flow.md). 

It fails at the step where Bob tries to buy datatokens: `tx_result = ocean.fixed_rate_exchange.buy_dt()`. 

The specific error is: `web3.exceptions.ContractLogicError: execution reverted: VM Exception while processing transaction: revert ERC20: transfer amount exceeds balance`

The problem: Bob doesn't have OCEAN. Further details below.

To fix: barge launching is supposed to put OCEAN into Bob's address. It's clearly not. We've seen this issue before. Looks like something got broken again.

**Details**

Here's the full call for Bob trying to buy datatokens: 
```python
tx_result = ocean.fixed_rate_exchange.buy_dt(
    exchange_id=exchange_id,
    datatoken_amount=ocean.to_wei(20),
    max_base_token_amount=ocean.to_wei(50),
    consume_market_swap_fee_address=ZERO_ADDRESS,
    consume_market_swap_fee_amount=0,
    from_wallet=bob_wallet,
)
```

Hypothesis: Bob doesn't have enough OCEAN.

To test hypothesis: query how much OCEAN Bob actually has:
```python
>>> ocean.web3.fromWei(OCEAN_token.balanceOf(bob_wallet.address), 'ether')
0
```

Info about Bob's wallet:
```python
>>> bob_private_key = os.getenv('TEST_PRIVATE_KEY2')
'0x1d751ded5a32226054cd2e71261039b65afb9ee1c746d055dd699b1150a5befc'
>>> bob_wallet = Wallet(ocean.web3, bob_private_key, config.block_confirmations, config.transaction_timeout)
>>> print(f"bob_wallet.address = '{bob_wallet.address}'")
bob_wallet.address = '0x529043886F21D9bc1AE0feDb751e34265a246e47'
```

**More details: full stack trace***

```python
>>> tx_result = ocean.fixed_rate_exchange.buy_dt(
...     exchange_id=exchange_id,
...     datatoken_amount=ocean.to_wei(20),
...     max_base_token_amount=ocean.to_wei(50),
...     consume_market_swap_fee_address=ZERO_ADDRESS,
...     consume_market_swap_fee_amount=0,
...     from_wallet=bob_wallet,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/models/fixed_rate_exchange.py", line 153, in buy_dt
    return self.send_transaction(
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/web3_internal/contract_base.py", line 216, in send_transaction
    return contract_function.transact(
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/web3_internal/web3_overrides/contract.py", line 71, in transact
    gas = cf.estimateGas(tx)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/contract.py", line 1039, in estimateGas
    return estimate_gas_for_function(
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/contract.py", line 1620, in estimate_gas_for_function
    return web3.eth.estimate_gas(estimate_transaction, block_identifier)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/eth.py", line 855, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 666, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 641, in cytoolz.functoolz.c_pipe
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/_utils/method_formatters.py", line 561, in raise_solidity_error_on_revert
    raise ContractLogicError(f'execution reverted: {response["error"]["message"]}')
web3.exceptions.ContractLogicError: execution reverted: VM Exception while processing transaction: revert ERC20: transfer amount exceeds balance
```

**Comment by trentmc** [comment]
There are three possible ways to solve:
1. ensure that Barge is properly minting OCEAN into the first N eth addresses of ganache, and that Bob is among those addresses
2. In the marketplace README itself, if Alice has OCEAN, then get Alice to send some OCEAN to Bob. 
3. Alice mints a fake token (not OCEAN) then sends some to Bob.

(1) is cleanest, I recommend it, though it has been finicky, we've had this issue before.

**Comment by mariacarmina** [comment]
> Towards solving, using approach of (1), the following may help. It's from the developers.md README. Maybe this envvar needs to be set somewhere before barge is started? Maybe barge doesn't set this anymore?
> 
> ```
> #needed to mint fake OCEAN for testing with ganache
> export FACTORY_DEPLOYER_PRIVATE_KEY=0xc594c6e5def4bab63ac29eed19a134c130388f74f019bc74b8f4389df2837a58
> ```
Previously we used `mint_fake_OCEAN` function at the beginning of every flow, for that we needed to export that env var. I have added back in `data-nfts-and-datatokens-flow.md` to be more visible. I have provided the fix in #908.

**Comment by mariacarmina** [comment]
Barge didn't and don't fill the accounts with OCEAN tokens. That address was set for `mint_fake_OCEAN()` function.

**Comment by trentmc** [comment]
Reopening.

This envvar shouldn't be added before it's needed.

Adding it in the first README - where it's not needed, adds to the complextity of that README. We want to keep the user flow as simple and clean as possible. 

Please fix. How:
- revert the last change
- put the change in the markteplace README. Not sooner.

**Comment by trentmc** [comment]
I'm working on #900 - UX tweaks for READMEs.

If the changes I recommend in the comment above are done, then it will cause conflict with my work on #900.

Therefore I will make those recommended changes as part of #900.

Therefore I can close _this_ issue. 

In the future let's always remember UX when we're fixing bugs, ie to avoid introducing unwanted complexity.
