### ISSUE TITLE
get_free_c2d_environment() call fails in C2D README

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#906]
**Describe the bug**
I'm going through the [C2D README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md). 

It all goes fine until this line:
```python
free_c2d_env = ocean.compute.get_free_c2d_environment(compute_service.service_endpoint)
```

Giving the traceback:
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/ocean/ocean_compute.py", line 165, in get_free_c2d_environment
    return next(env for env in environments if float(env["priceMin"]) == float(0))
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/ocean/ocean_compute.py", line 165, in <genexpr>
    return next(env for env in environments if float(env["priceMin"]) == float(0))
TypeError: string indices must be integers
```

**Comment by trentmc** [comment]
For reference, here's usage of that method:

```python
#how I found it
(venv) trentmc@trentmc-xps:~/code/ocean.py$ grep -r get_free_c2d_environment

#implementation
ocean_lib/ocean/ocean_compute.py:    def get_free_c2d_environment(self, service_endpoint: str) -> str:

#README
READMEs/c2d-flow.md:free_c2d_env = ocean.compute.get_free_c2d_environment(compute_service.service_endpoint)

#tests
tests/readmes/test_c2d_flow.py:    free_c2d_env = ocean.compute.get_free_c2d_environment(
tests/stress/compute_flow_with_threads.py:    free_c2d_env = ocean.compute.get_free_c2d_environment(
tests/integration/test_compute_flow.py:    free_c2d_env = ocean_instance.compute.get_free_c2d_environment(
```

**Comment by trentmc** [comment]
```
$ pytest tests/readmes/test_c2d_flow.py
...
tests/readmes/test_c2d_flow.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/readmes/test_c2d_flow.py:243: in c2d_flow_readme
    free_c2d_env = ocean.compute.get_free_c2d_environment(
venv/lib/python3.10/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
ocean_lib/ocean/ocean_compute.py:165: in get_free_c2d_environment
    return next(env for env in environments if float(env["priceMin"]) == float(0))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

.0 = <dict_keyiterator object at 0x7fbde2f07ce0>

>   return next(env for env in environments if float(env["priceMin"]) == float(0))
E   TypeError: string indices must be integers

ocean_lib/ocean/ocean_compute.py:165: TypeError
...
========================================== 2 failed in 72.85s (0:01:12) ===========================================
```

Both tests have the same error. I'm surprised that the CI isn't catching this.

Regardless, let's move to fix it...

**Comment by mariacarmina** [comment]
That error occurs if you are not running c2d environment. If you are running barge, make sure that you have `--with-c2d` flag and wait for the artifacts. I have also seen this error before and that was the fix.

**Comment by trentmc** [comment]
> That error occurs if you are not running c2d environment. If you are running barge, make sure that you have --with-c2d flag and wait for the artifacts.

Nope. I'm running that option. The issue exists.

**Comment by trentmc** [comment]
> had plenty of time for the artifacts to appear

While there was plenty of time for the artifacts to appear, they still _don't_. That is, the directory ~/.ocean/ocean-c2d remains empty 15 min after the start-ocean call. 

This is good news in that, at least we have narrowed down where the issue is:)

**Comment by trentmc** [comment]
Here's a log from the bash terminal running barge. Slightly messy, but maybe useful.

[temp.txt](https://github.com/oceanprotocol/ocean.py/files/9507213/temp.txt)


**Here are lines in temp.txt with "error":**

temp.txt error 1:
```text
aquarius_1         | 2022-09-06 21:01:51,456 - aquarius - ERROR - Can not get number of orders for subgraph development token address 0x55E144aB35A92a02a8947eA0DB1127b66Ec2aeeF
aquarius_1         | Traceback (most recent call last):
aquarius_1         |   File "/aquarius/aquarius/graphql.py", line 22, in get_number_orders
aquarius_1         |     client = get_client(chain_id)
aquarius_1         |   File "/aquarius/aquarius/graphql.py", line 60, in get_client
aquarius_1         |     return Client(transport=get_transport(chain_id), fetch_schema_from_transport=True)
aquarius_1         |   File "/aquarius/aquarius/graphql.py", line 48, in get_transport
aquarius_1         |     raise Exception("Subgraph not defined for this chain.")
aquarius_1         | Exception: Subgraph not defined for this chain.
```

temp.txt error 2:
```text
aquarius_1         | 2022-09-06 21:02:15,992 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:a9502bbf82886328dc04a993fb838ced3be752857d9f889cb04ad0597e431879
aquarius_1         | 2022-09-06 21:02:15,996 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:eca3c3c919374bf9d1b9f22ae28d1cf0481e99a12969c983554ed76a908f5166
provider_1         | 2022-09-06 21:02:15 19b0865fe3d9 ocean_provider.run[23] INFO incoming request = http, GET, 172.15.0.1, /?
provider_1         | 2022-09-06 21:02:15 19b0865fe3d9 ocean_provider.run[23] INFO root endpoint called
provider_1         | 2022-09-06 21:02:16 19b0865fe3d9 ocean_provider.run[23] INFO root endpoint response = <Response 901 bytes [200 OK]>
provider_1         | 2022-09-06 21:02:16 19b0865fe3d9 ocean_provider.run[22] INFO incoming request = http, GET, 172.15.0.1, /?
provider_1         | 2022-09-06 21:02:16 19b0865fe3d9 ocean_provider.run[22] INFO root endpoint called
provider_1         | 2022-09-06 21:02:16 19b0865fe3d9 ocean_provider.run[22] INFO root endpoint response = <Response 901 bytes [200 OK]>
provider_1         | 2022-09-06 21:02:16 19b0865fe3d9 ocean_provider.run[25] INFO incoming request = http, GET, 172.15.0.1, /api/services/computeEnvironments?
provider_1         | 2022-09-06 21:02:16 19b0865fe3d9 urllib3.connectionpool[25] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f38303820>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/operator/environments?chainId=8996
provider_1         | 2022-09-06 21:02:16 19b0865fe3d9 ocean_provider.run[25] ERROR error: HTTPConnectionPool(host='172.15.0.13', port=31000): Max retries exceeded with url: /api/v1/operator/environments?chainId=8996 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f38303a30>: Failed to establish a new connection: [Errno 111] Connection refused')), payload: b''
provider_1         | Traceback (most recent call last):
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in _new_conn
provider_1         |     conn = connection.create_connection(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 95, in create_connection
provider_1         |     raise err
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 85, in create_connection
provider_1         |     sock.connect(sa)
provider_1         | ConnectionRefusedError: [Errno 111] Connection refused
provider_1         | 
provider_1         | During handling of the above exception, another exception occurred:
provider_1         | 
provider_1         | Traceback (most recent call last):
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
provider_1         |     httplib_response = self._make_request(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
provider_1         |     conn.request(method, url, **httplib_request_kw)
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 239, in request
provider_1         |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 1234, in request
provider_1         |     self._send_request(method, url, body, headers, encode_chunked)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 1280, in _send_request
provider_1         |     self.endheaders(body, encode_chunked=encode_chunked)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 1229, in endheaders
provider_1         |     self._send_output(message_body, encode_chunked=encode_chunked)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 1008, in _send_output
provider_1         |     self.send(msg)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 948, in send
provider_1         |     self.connect()
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 205, in connect
provider_1         |     conn = self._new_conn()
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 186, in _new_conn
provider_1         |     raise NewConnectionError(
provider_1         | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4f38303a30>: Failed to establish a new connection: [Errno 111] Connection refused
provider_1         | 
provider_1         | During handling of the above exception, another exception occurred:
provider_1         | 
provider_1         | Traceback (most recent call last):
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
provider_1         |     resp = conn.urlopen(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
provider_1         |     return self.urlopen(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
provider_1         |     retries = retries.increment(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 592, in increment
provider_1         |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
provider_1         | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.15.0.13', port=31000): Max retries exceeded with url: /api/v1/operator/environments?chainId=8996 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f38303a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
provider_1         | 
provider_1         | During handling of the above exception, another exception occurred:
provider_1         | 
provider_1         | Traceback (most recent call last):
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1523, in full_dispatch_request
provider_1         |     rv = self.dispatch_request()
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1509, in dispatch_request
provider_1         |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
provider_1         |   File "/ocean-provider/ocean_provider/routes/compute.py", line 68, in decorated_function
provider_1         |     return f(*args, **kws)
provider_1         |   File "/ocean-provider/ocean_provider/routes/compute.py", line 564, in computeEnvironments
provider_1         |     response = jsonify(get_c2d_environments())
provider_1         |   File "/ocean-provider/ocean_provider/utils/compute_environments.py", line 24, in get_c2d_environments
provider_1         |     response = requests_session.get(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 600, in get
provider_1         |     return self.request("GET", url, **kwargs)
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
provider_1         |     resp = self.send(prep, **send_kwargs)
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
provider_1         |     r = adapter.send(request, **kwargs)
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 565, in send
provider_1         |     raise ConnectionError(e, request=request)
provider_1         | requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.15.0.13', port=31000): Max retries exceeded with url: /api/v1/operator/environments?chainId=8996 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f38303a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
aquarius_1         | 2022-09-06 21:02:16,019 - aquarius.events.processors - ERROR - encountered an error while updating the asset data to ES: 'updated'
```

temp.txt error 3:
```text
aquarius_1         | 2022-09-06 21:34:31,055 - aquarius.events.events_monitor - ERROR - Error updating purgatory list: ('Connection aborted.', OSError(0, 'Error')).
```

temp.txt error 4:
```text
elasticsearch_1    | {"type": "server", "timestamp": "2022-09-07T14:00:34,069Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "42cf650ba84e", "message": "JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-14071979640271421788, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -XX:MaxDirectMemorySize=268435456, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
```

temp.txt error 5:
```text
kindcluster_1      | Server:
kindcluster_1      | ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
kindcluster_1      | 2022-09-07 14:00:53,673 INFO spawned: 'dockerd' with pid 119
kindcluster_1      | Error on line 29
kindcluster_1      | Startup timeout, didn't become healthy after 3 mins.. details:
```

**Comment by trentmc** [comment]
Here's another log from the bash terminal running barge. Slightly messy, but maybe useful.

[temp2.txt](https://github.com/oceanprotocol/ocean.py/files/9507274/temp2.txt)

**Here are lines in temp2.txt with "error":**

temp2.txt error 1:
```
aquarius_1         | 2022-09-07 14:40:38,860 - aquarius - ERROR - Can not get number of orders for subgraph development token address 0x912Dc1368b15CB09998fDC0AB7c283AdebCE6cc6
aquarius_1         | Traceback (most recent call last):
aquarius_1         |   File "/aquarius/aquarius/graphql.py", line 22, in get_number_orders
aquarius_1         |     client = get_client(chain_id)
aquarius_1         |   File "/aquarius/aquarius/graphql.py", line 60, in get_client
aquarius_1         |     return Client(transport=get_transport(chain_id), fetch_schema_from_transport=True)
aquarius_1         |   File "/aquarius/aquarius/graphql.py", line 48, in get_transport
aquarius_1         |     raise Exception("Subgraph not defined for this chain.")
aquarius_1         | Exception: Subgraph not defined for this chain.
```

temp2.txt error 2:
```text
provider_1         | 2022-09-07 14:41:03 19b0865fe3d9 urllib3.connectionpool[28] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f321c8072e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/operator/environments?chainId=8996
provider_1         | 2022-09-07 14:41:03 19b0865fe3d9 ocean_provider.run[28] ERROR error: HTTPConnectionPool(host='172.15.0.13', port=31000): Max retries exceeded with url: /api/v1/operator/environments?chainId=8996 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f321c807490>: Failed to establish a new connection: [Errno 111] Connection refused')), payload: b''
provider_1         | Traceback (most recent call last):
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in _new_conn
provider_1         |     conn = connection.create_connection(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 95, in create_connection
provider_1         |     raise err
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 85, in create_connection
provider_1         |     sock.connect(sa)
provider_1         | ConnectionRefusedError: [Errno 111] Connection refused
provider_1         | 
provider_1         | During handling of the above exception, another exception occurred:
provider_1         | 
provider_1         | Traceback (most recent call last):
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
provider_1         |     httplib_response = self._make_request(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
provider_1         |     conn.request(method, url, **httplib_request_kw)
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 239, in request
provider_1         |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 1234, in request
provider_1         |     self._send_request(method, url, body, headers, encode_chunked)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 1280, in _send_request
provider_1         |     self.endheaders(body, encode_chunked=encode_chunked)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 1229, in endheaders
provider_1         |     self._send_output(message_body, encode_chunked=encode_chunked)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 1008, in _send_output
provider_1         |     self.send(msg)
provider_1         |   File "/usr/lib/python3.8/http/client.py", line 948, in send
provider_1         |     self.connect()
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 205, in connect
provider_1         |     conn = self._new_conn()
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 186, in _new_conn
provider_1         |     raise NewConnectionError(
provider_1         | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f321c807490>: Failed to establish a new connection: [Errno 111] Connection refused
provider_1         | 
provider_1         | During handling of the above exception, another exception occurred:
provider_1         | 
provider_1         | Traceback (most recent call last):
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
provider_1         |     resp = conn.urlopen(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
provider_1         |     return self.urlopen(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
provider_1         |     retries = retries.increment(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 592, in increment
provider_1         |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
provider_1         | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.15.0.13', port=31000): Max retries exceeded with url: /api/v1/operator/environments?chainId=8996 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f321c807490>: Failed to establish a new connection: [Errno 111] Connection refused'))
provider_1         | 
provider_1         | During handling of the above exception, another exception occurred:
provider_1         | 
provider_1         | Traceback (most recent call last):
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1523, in full_dispatch_request
provider_1         |     rv = self.dispatch_request()
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1509, in dispatch_request
provider_1         |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
provider_1         |   File "/ocean-provider/ocean_provider/routes/compute.py", line 68, in decorated_function
provider_1         |     return f(*args, **kws)
provider_1         |   File "/ocean-provider/ocean_provider/routes/compute.py", line 564, in computeEnvironments
provider_1         |     response = jsonify(get_c2d_environments())
provider_1         |   File "/ocean-provider/ocean_provider/utils/compute_environments.py", line 24, in get_c2d_environments
provider_1         |     response = requests_session.get(
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 600, in get
provider_1         |     return self.request("GET", url, **kwargs)
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
provider_1         |     resp = self.send(prep, **send_kwargs)
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
provider_1         |     r = adapter.send(request, **kwargs)
provider_1         |   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 565, in send
provider_1         |     raise ConnectionError(e, request=request)
provider_1         | requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.15.0.13', port=31000): Max retries exceeded with url: /api/v1/operator/environments?chainId=8996 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f321c807490>: Failed to establish a new connection: [Errno 111] Connection refused'))
aquarius_1         | 2022-09-07 14:41:03,759 - aquarius.events.processors - ERROR - encountered an error while updating the asset data to ES: 'updated'
```
