### ISSUE TITLE
Mumbai failure: "ExtraDataLengthError: The field extraData is 97 bytes, but should be 32"

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#920]
### Overview

I'm working with Mumbai. Any transaction fails with the same issue: "ExtraDataLengthError: The field extraData is 97 bytes, but should be 32"

### To reproduce
- Go through the new [simple-remote.md flow](https://github.com/oceanprotocol/ocean.py/blob/issue909-remote-c2d-readme/READMEs/simple-remote.md). (In [this branch](https://github.com/oceanprotocol/ocean.py/tree/issue909-remote-c2d-readme), though you don't need that since the branch currently only changes READMEs.)
- It will fail at the first real tx call, where I try to create a data nft. 
- Details below.

### Related
- Others have reported this issue for Ethereum chains, eg [here](https://stackoverflow.com/questions/70812529/the-field-extradata-is-97-bytes-but-should-be-32-it-is-quite-likely-that-you-a) and [here](https://github.com/blockchain-etl/ethereum-etl/issues/178). The fix was always the same.
- And in fact, we saw it before in Ocean. [#493](https://github.com/oceanprotocol/ocean.py/issues/493) encountered this exact issue when running on Rinkeby. However, [the fix](https://github.com/oceanprotocol/ocean.py/pull/494/files) was made specific to Rinkeby

### TODO
- Fix the issue, leveraging what was done for # 493.
- Do it at the same time as work on [#909](https://github.com/oceanprotocol/ocean.py/issues/909) (C2D README remote), for efficient testing. [Here's the PR](https://github.com/oceanprotocol/ocean.py/pull/913)

### Traceback Details

Here's the Python part of the flow, and the traceback.
```python
(venv) trentmc@trentmc-xps:~/code/play$ python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from ocean_lib.config import Config
>>> from ocean_lib.ocean.ocean import Ocean
>>> config = Config(os.getenv('OCEAN_CONFIG_FILE'))
>>> ocean = Ocean(config)
>>> import os
>>> from ocean_lib.web3_internal.wallet import Wallet
>>> alice_private_key = os.getenv('TEST_PRIVATE_KEY1')
>>> alice_wallet = Wallet(ocean.web3, alice_private_key, config.block_confirmations, config.transaction_timeout)
>>> data_nft = ocean.create_data_nft('NFT1', 'NFT1', alice_wallet)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/ocean/ocean.py", line 173, in create_data_nft
    tx_id = nft_factory.deploy_erc721_contract(
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/models/data_nft_factory.py", line 86, in deploy_erc721_contract
    return self.send_transaction(
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/web3_internal/contract_base.py", line 206, in send_transaction
    "gasPrice": self.get_gas_price(self.web3),
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/web3_internal/contract_base.py", line 182, in get_gas_price
    return web3.eth.generate_gas_price()
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/eth.py", line 973, in generate_gas_price
    return self._generate_gas_price(transaction_params)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/eth.py", line 213, in _generate_gas_price
    return self.gasPriceStrategy(self.web3, transaction_params)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/gas_strategies/time_based.py", line 208, in time_based_gas_price_strategy
    avg_block_time = _get_avg_block_time(web3, sample_size=sample_size)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/gas_strategies/time_based.py", line 47, in _get_avg_block_time
    latest = w3.eth.get_block('latest')
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/eth.py", line 677, in get_block
    return self._get_block(block_identifier, full_transactions)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 96, in middleware
    return _apply_response_formatters(method=method, response=response, **formatters)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 51, in _apply_response_formatters
    return _format_response("result", result_formatters[method])
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 47, in _format_response
    response, response_type, method_response_formatter(appropriate_response)
  File "cytoolz/functoolz.pyx", line 249, in cytoolz.functoolz.curry.__call__
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/eth_utils/applicators.py", line 72, in apply_formatter_if
    return formatter(value)
  File "cytoolz/functoolz.pyx", line 249, in cytoolz.functoolz.curry.__call__
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/eth_utils/applicators.py", line 84, in apply_formatters_to_dict
    yield key, formatters[key](item)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/web3/middleware/validation.py", line 75, in _check_extradata_length
    raise ExtraDataLengthError(
web3.exceptions.ExtraDataLengthError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer to http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: HexBytes('0xd682021083626f7288676f312e31372e33856c696e7578000000000000000000db786d1fced0b0dd32d754010110f793dd4c3a767631494948fee70bead59a741452d1f9c5da78fec498fbdba0b3c86e8fad8146054623fd703bceebe80f042200')
```

**Comment by trentmc** [comment]
Update: if I use the developer flow (git clone ocean.py) rather than the flow given above (import ocean lib) then I do _not_ hit the issue. Fishy...

**Comment by trentmc** [comment]
I fixed this as part of 
https://github.com/oceanprotocol/ocean.py/commit/a4fb91153891e2b68be90d4a5a7558bbb44e14d4

It's the changes in util.py
