### ISSUE TITLE
In running C2D README, got data_service_provider.py "result retrieval unsuccessful"

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#944]
**Describe the bug**
I was going through the C2D README, on the [PR](https://github.com/oceanprotocol/ocean.py/pull/913/files#diff-c8e25d9af3e6334fa1b6fcdb49e959cc8f5456fb4b2aad9c71879ed98650637f) to make things remote. Most changes were just about pointing to remote network, vs local. I was able to get all to run, until just before the end, at step 7 where "7. Bob monitors logs / algorithm output"

It went through the first part -  a loop until results are done - and found results so got `successful = True`.

Then when doing the next step:
```python
output = ocean.compute.compute_job_result_logs(
    DATASET_asset, compute_service, job_id, bob_wallet
)[0]
```

... it failed. 

Here's the traceback:
```text
Traceback (most recent call last):
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean_compute.py", line 134, in compute_job_result_logs
    result = self._data_provider.compute_job_result_logs(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/data_provider/data_service_provider.py", line 419, in compute_job_result_logs
    assert result, "result retrieval unsuccessful"
AssertionError: result retrieval unsuccessful
```

Of the four results coming back from `compute_job_result_logs()`, the first three gave a non-empty `result` (such that "assert result" passes). The fourth has a `result` of `b""`. That's what caused the failure.

**Comment by trentmc** [comment]
Let's debug. In the call...
```python
status = ocean.compute.status(DATASET_asset, compute_service, job_id, bob_wallet)
```

... here's what `status` looks like:
```python
>>> pprint(status)
{'agreementId': '0x0ceda4a6d5a23201141b4073a8f71b33c814a54497539fae3291197ed726fc64',
 'algoDID': 'did:op:ebf0f18aa191f0eedd734c1d0072841c729a306552ccfc23803920b6d8cd4840',
 'dateCreated': '1663621369.197587',
 'dateFinished': '1663621432.934751',
 'inputDID': ['did:op:6a14a78977b7ed76784f533627d6422d7d1b14048f97f00e0a8518cabd6a2488'],
 'jobId': '82130d71d65f47c4a76c6e46b923beb1',
 'ok': True,
 'owner': '0x529043886F21D9bc1AE0feDb751e34265a246e47',
 'removed': 0,
 'results': [{'filename': 'result', 'filesize': 1958, 'type': 'output'},
             {'filename': 'algorithm.log',
              'filesize': 185,
              'type': 'algorithmLog'},
             {'filename': 'configure.log',
              'filesize': 2319,
              'type': 'configrationLog'},
             {'filename': 'publish.log', 'filesize': 0, 'type': 'publishLog'}],
 'status': 70,
 'statusText': 'Job finished',
 'stopreq': 0}

>>> pprint(status["results"])
[{'filename': 'result', 'filesize': 1958, 'type': 'output'},
 {'filename': 'algorithm.log', 'filesize': 185, 'type': 'algorithmLog'},
 {'filename': 'configure.log', 'filesize': 2319, 'type': 'configrationLog'},
 {'filename': 'publish.log', 'filesize': 0, 'type': 'publishLog'}]
```

**Comment by trentmc** [comment]
Here's the bug: it should be perfectly acceptable for the fourth result, of type `publishLog`, to be empty, since it's just logging. (Maybe the other logs could be empty too, but let's worry about that another time.)

So then the minimally-invasive fix is: don't do the "assert result" check if it's of type `publishLog`
